// Revisão, Conquistas e Perfil (gostos e dificuldades editáveis; o app se reorganiza na hora).
(function () {
  const { esc } = TIE.u, C = TIE.C, I = TIE.icon, D = () => TIE.data;
  TIE.ui.flip = false;
  TIE.screens.revisao = {
    title: 'Revisão',
    render() {
      const s = TIE.store.s, R = TIE.review, q = R.queue(), card = q[0], n = q.length, done = TIE.game.summary().daily.cards || 0, desk = TIE.app.isDesktop();
      const title = n + (n === 1 ? ' cartão hoje' : ' cartões hoje'), pct = n ? Math.round(done / (done + n) * 100) : s.deck.length ? 100 : 0;
      const taken = s.deck.filter((c) => !/^Ep\. /.test(c.scene)).length, cur = TIE.guide.current();
      const empty = s.deck.length ? '<div class="card gr stack tc pop" style="--gap:10px;align-items:center">' + I('check', 40, 'style="color:var(--green)"') + '<div class="h2">Revisão em dia.</div><p class="p">Nenhum cartão para agora. O próximo volta ' + R.nextIn() + '.</p>' + C.btn('Ver um Extra', { go: 'extra', icon: 'tv' }) + '</div>'
        : '<div class="card stack tc pop" style="--gap:10px;align-items:center">' + I('cards', 40, 'style="color:var(--orange)"') + '<div class="h2">Seus cartões começam no episódio.</div><p class="p">Termine o Take a Look do episódio ' + TIE.u.pad2(cur.num) + ' e as palavras da cena viram os primeiros cartões.</p>' + C.btn('Continuar o episódio', { go: 'episodio/' + cur.num, icon: 'play' }) + '</div>';
      return { tabs: true, html: (desk ? '' : C.topbar({ kicker: 'Revisão', title, right: C.avatarBtn() })) + '<div class="scroll"><div class="wrap stack" style="--wrap:560px;--gap:16px">' + (desk ? '<div><div class="lbl">Revisão</div><h1 class="h1 mt4">' + title + '</h1></div>' : '') + '<div class="bar"><i style="width:' + pct + '%"></i></div>' +
        (card ? '<button class="flash" data-act="flip"><span class="row between"><span class="sm" style="font-weight:700">' + esc(card.scene) + '</span><span class="iconbtn" data-act="say" data-arg="' + esc(card.en) + '" aria-label="Ouvir" style="border:0;background:var(--cream)">' + I('speaker', 18) + '</span></span><span><span class="h1" style="display:block">' + esc(card.en) + '</span>' + (TIE.ui.flip ? '<span class="p-read pop" style="display:block;margin-top:14px;padding-top:14px;border-top:1.5px solid var(--line)">' + esc(card.pt) + (card.note ? '<span class="sm" style="display:block;margin-top:6px">' + esc(card.note) + '</span>' : '') + '</span>' : '') + '</span><span class="sm" style="font-weight:800;color:var(--blue)">' + (TIE.ui.flip ? 'Como foi? Escolha abaixo · +2 pontos' : 'Toque para ver a tradução') + '</span></button>' + (TIE.ui.flip ? '<div style="display:grid;grid-template-columns:repeat(4,1fr);gap:8px">' + R.GRADES.map(([l, t], i) => '<button class="card stack tc" data-act="grade" data-arg="' + i + '" style="--gap:2px;padding:10px 4px;align-items:center;border:2px solid var(--navy)"><span class="h3" style="font-size:.95rem">' + l + '</span><span class="xs">' + t + '</span></button>').join('') + '</div>' : '') : empty) +
        '<div class="card soft"><div class="lbl">De onde vêm os cartões</div><p class="p mt4">Do Take a Look (palavras da cena) e do Take Away (expressões-chave) de cada episódio que você faz' + (taken ? ', mais <b>' + taken + '</b> que você levou dos Extras e das conversas no Mic' : '. Toque numa palavra da legenda dos Extras para trazer mais') + '.' + (s.deck.length ? ' Seu baralho tem <b>' + s.deck.length + '</b> cartões.' : '') + '</p></div></div></div>' };
    }
  };
  TIE.act.flip = (a, el, ev) => { if (ev && ev.target.closest('[data-act="say"]')) return; TIE.ui.flip = !TIE.ui.flip; TIE.app.render(); };
  TIE.act.grade = (i) => { const c = TIE.review.queue()[0]; if (!c) return; TIE.ui.flip = false; TIE.review.grade(c.en, i); TIE.game.award('card'); TIE.app.render(); };

  TIE.screens.conquistas = {
    title: 'Conquistas',
    render() {
      const g = TIE.game.summary(), l = g.level, desk = TIE.app.isDesktop();
      return { tabs: true, html: (desk ? '' : C.topbar({ back: 'inicio', kicker: 'Sua caminhada', title: 'Conquistas' })) + '<div class="scroll"><div class="wrap stack" style="--wrap:760px;--gap:16px">' + (desk ? '<h1 class="h1">Conquistas</h1>' : '') +
        '<div class="card navy stack" style="--gap:12px"><div class="row between">' + C.levelpill() + '<span class="h2" style="color:#fff">' + g.points + ' pontos</span></div><div class="bar"><i style="width:' + l.pct + '%;background:var(--orange)"></i></div><div class="xs" style="color:var(--onNavy)">' + (l.next ? 'Faltam ' + (l.next - g.points) + ' pontos para o nível ' + (l.n + 1) + ' · ' + TIE.game.LEVELS[l.n][1] : 'Nível máximo alcançado.') + '</div></div>' + C.gamebar() +
        '<div class="card stack" style="--gap:8px"><div class="row between"><div class="lbl">Missões do dia</div><span class="xs">' + g.missions.filter((m) => m.done).length + '/' + g.missions.length + '</span></div>' + C.missions(g.missions) + '</div>' +
        '<div class="stack" style="--gap:8px"><div class="lbl">Medalhas · ' + g.badges.filter((b) => b.has).length + ' de ' + g.badges.length + '</div><div class="badges">' + g.badges.map((b) => '<div class="medal' + (b.has ? '' : ' locked') + '"><span class="ic">' + I(b.icon, 24) + '</span><b>' + esc(b.t) + '</b><span class="xs">' + esc(b.s) + '</span></div>').join('') + '</div></div>' +
        '<div class="card soft"><div class="lbl">Como ganhar pontos</div><div class="stack mt8" style="--gap:4px">' + [['Etapa do episódio', 10], ['Episódio inteiro', 40], ['Exercício certo', 5], ['Pronúncia nota 8+', 15], ['Fala no Mic', 5], ['Conversa inteira', 30], ['Extra até o fim', 20], ['Cartão revisado', 2], ['Missão do dia', 15], ['Teste do e-book', 50]].map(([t, v]) => '<div class="row between"><span class="p">' + t + '</span><span class="pill gold">+' + v + '</span></div>').join('') + '</div></div></div></div>' };
    }
  };

  TIE.screens.perfil = {
    title: 'Você',
    render() {
      const s = TIE.store.s, p = s.profile, O = D().ONB, P = TIE.personalize.build(p), st = s.settings, g = TIE.game.summary();
      const sec = (title, inner, sub) => '<div class="card stack" style="--gap:10px"><div><div class="lbl">' + title + '</div>' + (sub ? '<div class="xs mt4">' + sub + '</div>' : '') + '</div>' + inner + '</div>';
      const chips = (list, sel, act, single) => '<div class="chips">' + list.map((x) => { const k = Array.isArray(x) ? x[0] : x.k, l = Array.isArray(x) ? x[1] : x.t; return C.chip(l, { on: single ? sel === k : sel.includes(k), act, arg: k }); }).join('') + '</div>';
      const genreList = p.formats.flatMap((f) => O.GENRES[f]).filter((g2, i, a) => a.findIndex((x) => x[0] === g2[0]) === i);
      const setting = (t, sub, k) => '<div class="listrow"><div class="grow"><div class="h3">' + t + '</div><div class="sm">' + sub + '</div></div>' + C.toggle(st[k], 'setToggle', k, t) + '</div>';
      const sessions = s.maggie.sessions.slice(0, 4);
      if (!p.reminders) p.reminders = TIE.personalize.reminders(p);
      const remRows = () => '<div class="stack" style="--gap:8px">' + p.reminders.map((t, i) => '<div class="row" style="--gap:10px">' + I('bell', 20, 'style="color:var(--blue);flex:none"') + '<input class="input grow" id="pf-rem' + i + '" type="time" value="' + esc(t) + '" data-model="profile.reminders.' + i + '" aria-label="Horário do lembrete ' + (i + 1) + '"><button class="iconbtn" data-act="pfRemDel" data-arg="' + i + '" aria-label="Remover lembrete ' + (i + 1) + '">' + I('close', 18) + '</button></div>').join('') + (p.reminders.length ? '' : '<div class="sm">Sem lembrete.</div>') + (p.reminders.length < O.REMIND_MAX ? '<button class="btn light compact" data-act="pfRemAdd" style="align-self:flex-start">' + I('plus', 18) + '<span>Adicionar lembrete</span></button>' : '') + '</div>';
      return { tabs: true, html: '<div class="scroll"><div class="wrap stack" style="--wrap:760px;--gap:14px;padding-top:16px">' +
        '<div class="card navy row" style="--gap:14px">' + C.userPic(72) + '<div class="grow"><div class="h1" style="color:#fff">' + esc(p.name) + '</div><div class="xs mt4" style="color:var(--onNavy)">' + esc(s.user && s.user.email || '') + '</div><div class="row mt8 wrapx" style="--gap:6px">' + C.levelpill() + '<span class="pill" style="background:var(--navy2);color:#fff">' + P.level.cefr + ' · Temporada ' + P.level.season + '</span></div></div></div>' + C.gamebar() +
        sec('Sua foto', '<div class="row wrapx" style="--gap:8px">' + [1, 2, 3, 4, 5, 6].map((i) => '<button class="avpick' + (!p.photo && (p.avatar || 1) === i ? ' on' : '') + '" data-act="pfAvatar" data-arg="' + i + '" aria-label="Avatar ' + i + '"><img src="' + TIE.avatar.DIR + 'user-' + i + '.webp" alt=""></button>').join('') + '</div><label class="btn light compact" style="align-self:flex-start;cursor:pointer">' + I('plus', 18) + '<span>' + (p.photo ? 'Trocar a minha foto' : 'Enviar a minha foto') + '</span><input type="file" accept="image/*" data-file="pfPhoto" hidden></label>' + (p.photo ? '<button class="btn link" data-act="pfPhotoClear" style="align-self:flex-start">Usar um avatar em vez da foto</button>' : ''), 'Escolha um avatar ou envie uma foto. No protótipo, a foto fica só neste navegador.') +
        sec('Seu assistente no Mic', C.assistPicker('pfAssistant'), 'Quem conversa com você: cada personagem tem voz e jeito de falar próprios.') + '<div class="fb tip"><b>O app se reorganiza na hora.</b> Mude um gosto ou uma dificuldade e veja Hoje, o EXTRA e as missões do Mic mudarem.</div>' +
        sec('Seu nível', chips(O.LEVELS, p.level, 'pfLevel', true)) + sec('O que você busca', chips(O.GOALS, p.goals, 'pfGoal'), 'Até 3. Define as missões do Mic.') + sec('Formatos que você curte', chips(O.FORMATS, p.formats, 'pfFormat'), 'Define a sua prateleira no EXTRA.') + (genreList.length ? sec('Gêneros', chips(genreList, p.genres, 'pfGenre')) : '') + sec('Fora da tela', chips(O.THEMES, p.themes, 'pfTheme')) +
        sec('O que trava', chips(O.DIFFS, p.diffs, 'pfDiff') + (p.diffs.length > 1 ? '<div class="lbl mt8">O que trava mais · vira o foco da semana</div>' + chips(p.diffs.map((k) => O.DIFFS.find((x) => x.k === k)), p.mainDiff, 'pfMain', true) : '')) +
        sec('Jeito de aprender', chips(O.STYLES.map((x) => [x[0], x[1]]), p.styles, 'pfStyle') + '<div class="lbl mt8">Quando erra, ' + TIE.assist.the() + '…</div>' + chips(O.FEEDBACK, p.feedback, 'pfFeedback', true)) +
        sec('Ritmo', '<div class="days">' + O.DAYS.map((l, i) => '<button class="' + (p.days.includes(i) ? 'on' : '') + '" data-act="pfDay" data-arg="' + i + '">' + l + '</button>').join('') + '</div><div class="lbl mt8">Minutos por dia · meta de ' + TIE.game.goalTarget() + ' pontos</div>' + chips(O.MINUTES, p.minutes, 'pfMin', true) + '<div class="lbl mt8">Lembretes</div>' + remRows()) +
        sec('Do zero ao B2', '<div style="display:grid;grid-template-columns:repeat(8,1fr);gap:5px">' + ['A1', 'A1+', 'A2', 'A2+', 'B1', 'B1+', 'B2', 'B2+'].map((c, i) => '<div class="stack tc" style="--gap:5px;align-items:center"><div style="width:100%;height:46px;border-radius:6px;background:' + (i === P.level.season - 1 ? 'linear-gradient(to top,var(--blue) 22%,var(--line) 22%)' : i < P.level.season - 1 ? 'var(--blue)' : 'var(--line)') + '"></div><span class="xs" style="font-weight:800">' + c + '</span></div>').join('') + '</div>') +
        (sessions.length ? sec('Conversas no Mic', sessions.map((x) => '<a class="listrow" href="#/maggie/relatorio/' + x.id + '" style="color:inherit"><span class="iconbtn" style="border:0;background:var(--cream)">' + I('mic', 18) + '</span><div class="grow"><div class="h3">' + esc(x.mode === 'missao' ? D().MAGGIE.MISSIONS[x.mission].t : D().MAGGIE.MODES.find((m) => m.k === x.mode).t) + '</div><div class="sm">' + new Date(x.at).toLocaleDateString('pt-BR') + ' · ' + x.turns.filter((t) => t.who === 'me').length + ' falas</div></div>' + I('next', 18) + '</a>').join('')) : '') +
        sec('Leitura, som e efeitos', '<div class="listrow"><div class="grow"><div class="h3">Tamanho do texto</div><div class="sm">Vale para o app inteiro</div></div><div class="seg">' + [[1, 'A'], [1.12, 'A+'], [1.25, 'A++']].map(([v, l]) => '<button class="' + (st.ts === v ? 'on' : '') + '" data-act="setTs" data-arg="' + v + '">' + l + '</button>').join('') + '</div></div>' + setting('Sons', 'Cliques, acertos e trilha das músicas', 'sound') + setting('Confete e animações', 'Comemorações de meta e nível', 'fx') + setting('Voz HD dos personagens', TIE.ai.online ? 'Voz do Gemini pelo servidor local.' : 'Precisa do servidor local ligado', 'hd') + setting('Começar em 0,75×', 'Velocidade inicial do diálogo', 'slow') + setting('Lembrete de episódio', 'Quando o próximo liberar', 'remind')) +
        sec('Plano', '<div class="listrow"><div class="grow"><div class="h3">Plano Padrão</div><div class="sm">60 min de conversa no Mic por mês · ' + (60 - Math.round(s.maggie.secLeft / 60)) + ' usados</div></div><span class="sm" style="font-weight:800;color:var(--blue)">Gerenciar</span></div>') +
        '<div class="row wrapx" style="--gap:10px">' + C.btn('Sair', { kind: 'ghost', act: 'logout', icon: 'logout' }) + C.btn('Apagar dados do protótipo', { kind: 'link', act: 'wipe' }) + '</div></div></div>' };
    }
  };
  const P = () => TIE.store.s.profile;
  const tg = (arr, k, max) => { const i = arr.indexOf(k); if (i >= 0) arr.splice(i, 1); else if (!max || arr.length < max) arr.push(k); else { TIE.app.toast('Até ' + max + '. Desmarque um para trocar.'); } };
  const save = (msg) => { TIE.store.save(); TIE.app.render(); if (msg) TIE.app.toast(msg); };
  TIE.act.pfAvatar = (i) => { P().avatar = +i; P().photo = ''; save(); };
  TIE.act.pfPhotoClear = () => { P().photo = ''; save(); };
  TIE.act.pfPhoto = (file) => { const img = new Image(), url = URL.createObjectURL(file); img.onload = () => { const c = document.createElement('canvas'), S = 256, k = Math.max(S / img.width, S / img.height); c.width = S; c.height = S; const g = c.getContext('2d'); g.drawImage(img, (S - img.width * k) / 2, (S - img.height * k) / 2, img.width * k, img.height * k); P().photo = c.toDataURL('image/jpeg', .85); URL.revokeObjectURL(url); save('Foto atualizada.'); }; img.src = url; };
  TIE.act.pfAssistant = (k) => { const a = TIE.assist.get(k); P().assistant = a.k; save(); TIE.speech.say(a.hello.en, { who: a.name }); };
  TIE.act.pfLevel = (k) => { P().level = k; save('Nível atualizado.'); }; TIE.act.pfGoal = (k) => { tg(P().goals, k, 3); save(); }; TIE.act.pfFormat = (k) => { tg(P().formats, k); save('Prateleira do EXTRA reorganizada.'); }; TIE.act.pfGenre = (k) => { tg(P().genres, k); save(); }; TIE.act.pfTheme = (k) => { tg(P().themes, k); save(); }; TIE.act.pfStyle = (k) => { tg(P().styles, k); save(); }; TIE.act.pfFeedback = (k) => { P().feedback = k; save(); }; TIE.act.pfDay = (v) => { tg(P().days, +v); P().days.sort(); save(); }; TIE.act.pfMin = (v) => { P().minutes = +v; save('Meta diária: ' + TIE.game.goalTarget() + ' pontos.'); }; TIE.act.pfRemAdd = () => { const R = P().reminders; R.push(['07:00', '12:30', '20:00', '09:00', '18:00', '22:00'].find((t) => !R.includes(t)) || '12:00'); save(); }; TIE.act.pfRemDel = (i) => { P().reminders.splice(+i, 1); save(); };
  TIE.act.pfDiff = (k) => { const p = P(); tg(p.diffs, k); if (!p.diffs.includes(p.mainDiff)) p.mainDiff = p.diffs[0] || ''; save(); }; TIE.act.pfMain = (k) => { P().mainDiff = k; save('Foco da semana atualizado.'); };
  TIE.act.setToggle = (k) => { const st = TIE.store.s.settings; if (k === 'hd' && !st.hd && !TIE.ai.online) { TIE.app.toast('Ligue o servidor local para usar a voz HD.'); return; } st[k] = !st[k]; if (k === 'sound' && !st.sound) TIE.sound.synth.stop(); save(); };
  TIE.act.setTs = (v) => { TIE.store.s.settings.ts = +v; save(); };
  TIE.act.logout = () => { TIE.speech.stop(); TIE.store.set({ user: null, profile: null }, { silent: true }); TIE.router.go('entrar'); };
  TIE.act.wipe = () => { if (!confirm('Apagar tudo o que o protótipo guardou neste navegador?')) return; TIE.store.reset(); TIE.router.go('entrar'); TIE.app.render(); };
})();
