// EXTRA: carrossel de capas, prateleiras por formato, detalhe, player da cena (legendas, palavra tocável,
// dublagem), músicas com karaokê de lacunas e o desafio relâmpago.
(function () {
  const { esc, pick, shuffle, pad2 } = TIE.u, C = TIE.C, I = TIE.icon, D = () => TIE.data;
  const byId = (id) => D().EXTRAS.find((x) => x.id === id);
  const SHELVES = [['pra-voce', 'Pra você'], ['series', 'Séries'], ['novelas', 'Novelas'], ['filmes', 'Filmes'], ['animes', 'Animes'], ['musica', 'Música'], ['games', 'Games']];
  TIE.ui.shelf = TIE.ui.shelf || 'pra-voce';
  const addCard = (en, pt, scene) => TIE.review.add(en, pt, scene);
  TIE.addCard = addCard;
  const album = (k) => '<button class="cover" data-go="extra/musica/' + k.id + '" style="width:150px"><div class="art" style="aspect-ratio:1"><img src="' + k.img + '" alt="" loading="lazy"><span class="pill lvl lv">' + k.level + '</span></div><div class="ttl">' + esc(k.title) + '</div><div class="xs">' + esc(k.sub) + '</div>' + (k.why ? '<div class="why">' + esc(k.why) + '</div>' : '') + '</button>';
  const rail = (title, items, sub) => items.length ? '<section class="stack" style="--gap:8px"><div><div class="h2" style="color:#fff">' + esc(title) + '</div>' + (sub ? '<div class="xs mt4">' + esc(sub) + '</div>' : '') + '</div><div class="rail">' + items.join('') + '</div></section>' : '';

  TIE.screens.extra = {
    title: 'EXTRA',
    render() {
      const s = TIE.store.s, p = s.profile, P = TIE.personalize.build(p), sh = TIE.ui.shelf, desk = TIE.app.isDesktop();
      const open = P.extras.filter((x) => !x.locked), soon = P.extras.filter((x) => x.locked);
      const tabs = '<div class="shelf-tabs">' + SHELVES.map(([k, l]) => '<button class="' + (sh === k ? 'on' : '') + '" data-act="shelf" data-arg="' + k + '">' + l + '</button>').join('') + '<button data-go="extra/desafio" style="background:var(--orange);color:#fff">' + I('game', 18, 'style="vertical-align:-4px"') + ' Desafio</button></div>';
      let body = '';
      if (sh === 'pra-voce') body = C.flow(open.slice(0, 7), 'flow-home') + '<div class="tc xs">Arraste ou toque numa capa. Sugestões pelo que você marcou: ' + esc(p.formats.map((f) => TIE.personalize.FORMAT_WORD[f]).join(', ')) + '.</div>' + rail(open[0].why, open.slice(0, 6).map((x) => C.cover(x)), 'Os mais parecidos com o seu perfil') + p.formats.filter((f) => f !== 'musica').map((f) => { const it = open.filter((x) => x.format === f); return it.length ? rail(D().ONB.FORMATS.find((y) => y.k === f).t, it.map((x) => C.cover(x, { why: false }))) : ''; }).join('') + rail('Música', P.albums.map(album), 'Karaokê com lacunas') + '<a class="card row" href="#/extra/desafio" style="--gap:14px;background:var(--orange);border-color:var(--orange);color:#fff">' + I('game', 30) + '<span class="grow"><span class="h3" style="display:block;color:#fff">Desafio relâmpago · 60 segundos</span><span class="xs" style="color:#fff">As falas dos Extras caem na tela. Escolha a tradução certa. Recorde: ' + s.extras.best + ' pontos</span></span>' + I('next', 22) + '</a>' + rail('Estreias sexta', soon.map((x) => C.cover(x, { why: false })));
      else if (sh === 'musica') body = '<div style="display:grid;grid-template-columns:repeat(auto-fill,minmax(150px,1fr));gap:16px">' + P.albums.map(album).join('') + '</div>';
      else { const list = P.extras.filter((x) => x.format === sh); body = list.length ? '<div style="display:grid;grid-template-columns:repeat(auto-fill,minmax(150px,1fr));gap:18px 14px">' + list.map((x) => C.cover(x)).join('') + '</div>' : '<div class="card dash" style="color:var(--onNavy);border-color:var(--navy3)">Nada nesta prateleira ainda. Toda sexta chega título novo.</div>'; }
      return { tabs: true, theme: 'navy', html: '<div class="on-navy" style="display:flex;flex-direction:column;flex:1;min-height:0"><header class="topbar"><div class="ttl"><div class="lbl">Séries, novelas, filmes, animes e música</div><div class="h1" style="color:#fff">EXTRA</div></div>' + (desk ? '' : C.avatarBtn()) + '</header><div class="scroll"><div class="wrap stack" style="--wrap:1120px;--gap:20px;padding-top:4px">' + tabs + body + '</div></div></div>' };
    },
    after() { if (this.fl) this.fl.destroy(); this.fl = C.flowMount(document.getElementById('flow-home')); },
    leave() { if (this.fl) { this.fl.destroy(); this.fl = null; } }
  };
  TIE.act.shelf = (k) => { TIE.ui.shelf = k; TIE.app.render(); };

  TIE.screens.extraDetail = {
    title: 'EXTRA',
    render(p) {
      const x0 = byId(p.id); if (!x0) { setTimeout(() => TIE.router.replace('extra'), 0); return { html: '' }; }
      const P = TIE.personalize.build(TIE.store.s.profile), x = P.extras.find((e) => e.id === x0.id);
      return { tabs: true, theme: 'navy', nav: 'extra', html: '<div class="on-navy" style="display:flex;flex-direction:column;flex:1;min-height:0">' + C.topbar({ back: 'extra', kicker: x.kind, title: x.title }) + '<div class="scroll"><div class="hero-extra" style="border-radius:0;min-height:260px"><img src="' + x.scene + '" alt=""><div class="shade"></div><div class="inner stack" style="--gap:8px"><div class="row wrapx" style="--gap:8px"><span class="pill" style="background:var(--navyD);color:#fff">' + esc(x.kind) + '</span><span class="pill lvl">' + x.level + '</span><span class="pill" style="background:var(--navyD);color:#fff">' + x.dur + '</span></div><div class="h1" style="color:#fff">' + esc(x.title) + '</div><div class="sm">' + esc(x.ep) + '</div></div></div>' +
        '<div class="wrap stack" style="--wrap:820px;--gap:16px"><p class="p-read">' + esc(x.synopsis) + '</p><div class="xs" style="color:#FFB08F;font-weight:800">' + esc(x.why) + '</div><div class="chips">' + x.cast.map(([n, ini, c]) => '<span class="pill" style="background:var(--navy2);color:#fff;min-height:36px"><b style="width:26px;height:26px;border-radius:50%;background:' + c + ';display:inline-flex;align-items:center;justify-content:center;font-size:.7rem">' + ini + '</b>' + n + '</span>').join('') + '</div>' +
        (x.locked ? '<div class="card"><div class="h3" style="color:#fff">Estreia sexta.</div><div class="mt12">' + C.btn('Me avise quando chegar', { act: 'notifyMe', icon: 'clock', kind: 'light' }) + '</div></div>' : '<div class="stack" style="--gap:10px">' + C.btn('Assistir com legendas · +20 pontos', { go: 'extra/' + x.id + '/assistir', icon: 'play', cls: 'block' }) + C.btn('Dublar o ' + x.dub + ' · +10 por fala', { kind: 'light', go: 'extra/' + x.id + '/assistir?dub=1', icon: 'mic', cls: 'block' }) + C.btn('Conversar com ' + TIE.assist.the() + ' sobre isto', { kind: 'ghost', go: 'maggie?modo=extra&x=' + x.id, icon: 'chat', cls: 'block' }) + '</div><div class="card"><div class="lbl">Vocabulário da cena</div><div class="stack mt8" style="--gap:0">' + x.vocab.map(([en, pt]) => '<div class="listrow"><button class="en grow" data-act="say" data-arg="' + esc(en) + '" style="text-align:left;color:#fff">' + esc(en) + '</button><span style="color:var(--onNavy)">' + esc(pt) + '</span></div>').join('') + '</div></div>') + '</div></div></div>' };
    }
  };
  TIE.act.notifyMe = () => TIE.app.toast('Combinado. Você recebe um aviso na sexta.');

  let V = null;
  const vfresh = (x, dub) => ({ id: x.id, line: 0, playing: false, subs: TIE.personalize.build(TIE.store.s.profile).defaults.subs, dub: !!dub, dubState: '', word: null, saved: 0, end: false, fb: null, awarded: false });
  function vstop() { TIE.speech.stop(); if (V) { V.playing = false; clearTimeout(V.t); } }
  TIE.screens.extraPlay = {
    title: 'Assistindo',
    render(p, q) {
      const x = byId(p.id); if (!x || x.locked) { setTimeout(() => TIE.router.replace('extra/' + p.id), 0); return { html: '' }; }
      if (!V || V.id !== x.id) V = vfresh(x, q.dub === '1');
      const L = x.lines[V.line], mine = V.dub && L.who === x.dub;
      const words = L.en.split(/(\s+)/).map((w) => /\s+/.test(w) ? w : '<span class="w" data-act="word" data-arg="' + esc(w) + '">' + esc(w) + '</span>').join('');
      const subtitle = V.end ? '' : mine && V.dubState !== 'done' ? '<div class="sub"><span class="mute">' + I('mic', 16, 'style="vertical-align:-3px"') + ' Sua vez, ' + esc(x.dub) + '</span><span class="en">' + esc(L.en) + '</span></div>' : V.subs === 'off' ? '' : '<div class="sub"><span class="who">' + esc(L.who.toUpperCase()) + '</span><span class="en">' + words + '</span>' + (V.subs === 'both' ? '<span class="ptl">' + esc(L.pt) + '</span>' : '') + '</div>';
      const scene = '<div class="scene"><div class="img' + (V.playing ? '' : ' paused') + '" style="background-image:url(' + x.scene + ')"></div><span class="tag pill" style="background:rgba(10,30,63,.7);color:#fff">' + (V.dub ? I('mic', 12) + ' Dublagem' : esc(x.ep)) + '</span>' + subtitle + '</div>';
      const dubPanel = mine && !V.end ? '<div class="card paper stack pop" style="--gap:10px"><div class="lbl or">Sua vez · a fala é do ' + esc(x.dub) + '</div><div class="h2">' + esc(L.en) + '</div><div class="sm">' + esc(L.pt) + '</div>' + (V.dubState === 'rec' ? '<div class="waves rec">' + Array.from({ length: 14 }, (_, i) => '<i style="height:' + (14 + ((i * 11) % 30)) + 'px;animation-delay:' + i * .06 + 's"></i>').join('') + '</div>' : '') + (V.fb ? '<div class="fb ' + (V.fb.score >= 8 ? 'ok' : 'fix') + '"><b>' + V.fb.score + '/10.</b> ' + esc(V.fb.praise_pt) + (V.fb.issues || []).map((i) => ' <b>' + esc(i.word) + ':</b> ' + esc(i.tip_pt)).join('') + '</div>' : '') + '<div class="row wrapx" style="--gap:8px">' + (V.dubState === 'done' ? C.btn('Seguir a cena', { act: 'vNext', iconR: 'next', kind: 'compact' }) + C.btn('Dublar de novo', { act: 'vDub', kind: 'ghost compact' }) : C.btn(V.dubState === 'rec' ? 'Parar' : V.dubState === 'busy' ? 'Avaliando…' : 'Gravar a fala', { act: 'vDub', icon: V.dubState === 'rec' ? 'stop' : 'mic', kind: 'compact' }) + C.btn('Ouvir antes', { act: 'say', arg: L.en, kind: 'ghost compact', icon: 'speaker' }) + C.btn('Pular', { act: 'vNext', kind: 'link' })) + '</div></div>' : '';
      const endCard = V.end ? '<div class="card paper stack pop" style="--gap:12px"><div class="lbl or">Fim da cena</div><div class="h2">Você viu ' + x.lines.length + ' falas' + (V.saved ? ' e levou ' + V.saved + (V.saved > 1 ? ' palavras' : ' palavra') + ' para a Revisão' : '') + '.</div>' + (V.dub ? '<p class="p">Média na dublagem: ' + (TIE.store.s.extras.dubs[x.id] || '—') + '/10.</p>' : '') + '<div class="stack" style="--gap:8px">' + C.btn('Contar para ' + TIE.assist.the() + ' o que aconteceu', { go: 'maggie?modo=extra&x=' + x.id, icon: 'mic', cls: 'block' }) + C.btn('Desafio com estas falas', { kind: 'navy', go: 'extra/desafio?x=' + x.id, icon: 'game', cls: 'block' }) + C.btn('Assistir de novo', { kind: 'ghost', act: 'vRewind', cls: 'block' }) + '</div></div>' : '';
      const lines = '<div class="lines">' + x.lines.map((l, i) => '<button class="line' + (i === V.line ? ' on' : '') + (V.dub && l.who === x.dub ? ' dub' : '') + '" data-act="vLine" data-arg="' + i + '" id="vl' + i + '"><div class="who">' + esc(l.who.toUpperCase()) + (V.dub && l.who === x.dub ? ' · VOCÊ' : '') + '</div><div class="en">' + esc(l.en) + '</div>' + (V.subs === 'both' ? '<div class="pt">' + esc(l.pt) + '</div>' : '') + '</button>').join('') + '</div>';
      const controls = '<div class="controls"><button class="iconbtn" data-act="vPrev" aria-label="Anterior">' + I('back', 20) + '</button><button class="playbtn" data-act="vPlay" aria-label="' + (V.playing ? 'Pausar' : 'Assistir') + '">' + I(V.playing ? 'pause' : 'play', 24) + '</button><button class="iconbtn" data-act="vNext" aria-label="Próxima">' + I('next', 20) + '</button><button class="iconbtn" data-act="vRepeat" aria-label="Repetir devagar" title="Repetir em 0,75×">' + I('repeat', 20) + '</button><span class="grow"></span><div class="seg">' + [['en', 'EN'], ['both', 'EN+PT'], ['off', 'Sem']].map(([k, l]) => '<button class="' + (V.subs === k ? 'on' : '') + '" data-act="vSubs" data-arg="' + k + '">' + l + '</button>').join('') + '</div></div><div class="row"><button class="chip' + (V.dub ? ' on' : '') + '" data-act="vDubMode"><span class="ck">' + (V.dub ? I('check', 12) : '') + '</span>Dublar o ' + esc(x.dub) + '</button><span class="xs">Toque numa palavra da legenda para salvar.</span></div>';
      const wordPop = V.word ? '<div class="overlay"><div class="scrim" data-act="wordClose"></div><div class="sheet"><div class="grab"></div><div class="row between"><div class="h1">' + esc(V.word.w) + '</div><button class="iconbtn" data-act="say" data-arg="' + esc(V.word.w) + '" aria-label="Ouvir">' + I('speaker', 20) + '</button></div>' + (V.word.meaning ? '<div class="h3 mt8">' + esc(V.word.meaning) + '</div>' : '') + '<div class="card soft mt12"><div class="en">' + esc(V.word.line.en) + '</div><div class="pt mt4">' + esc(V.word.line.pt) + '</div></div><div class="stack mt16" style="--gap:8px">' + C.btn('Levar para a Revisão · +3', { act: 'wordSave', icon: 'plus', cls: 'block' }) + C.btn('Fechar', { kind: 'ghost', act: 'wordClose', cls: 'block' }) + '</div></div></div>' : '';
      const desk = TIE.app.isDesktop();
      return { theme: 'navy', overlay: wordPop, html: '<div class="on-navy" style="display:flex;flex-direction:column;flex:1;min-height:0">' + C.topbar({ back: 'extra/' + x.id, kicker: x.kind + ' · ' + x.ep, title: x.title, right: C.demoBadge() }) + '<div class="scroll"><div class="wrap" style="--wrap:1100px">' + (desk ? '<div style="display:grid;grid-template-columns:minmax(0,1.4fr) minmax(0,1fr);gap:22px;align-items:start"><div class="stack" style="--gap:14px">' + scene + controls + dubPanel + endCard + '</div><div class="stack" style="--gap:8px"><div class="lbl">Roteiro da cena</div>' + lines + '</div></div>' : '<div class="stack" style="--gap:14px">' + scene + controls + dubPanel + endCard + '<div class="lbl mt8">Roteiro da cena</div>' + lines + '</div>') + '</div></div></div>' };
    },
    after() { if (V && V.playing) { const el = document.getElementById('vl' + V.line); if (el) el.scrollIntoView({ block: 'nearest', behavior: 'smooth' }); } },
    leave() { vstop(); V = null; }
  };
  const X = () => byId(V.id), vre = () => TIE.app.render();
  function finishScene() { const x = X(); V.playing = false; V.end = true; TIE.store.s.extras.seen[x.id] = true; TIE.store.s.extras.lastId = x.id; TIE.store.save(); if (!V.awarded) { V.awarded = true; TIE.game.award('extra'); } vre(); }
  function vplayFrom(i) { const x = X(); if (!V || !V.playing) return; if (i >= x.lines.length) return finishScene(); V.line = i; V.dubState = ''; V.fb = null; const L = x.lines[i]; if (V.dub && L.who === x.dub) { V.playing = false; return vre(); } vre(); TIE.speech.say(L.en, { who: L.who }).then(() => { if (V && V.playing && V.line === i) V.t = setTimeout(() => vplayFrom(i + 1), 350); }); }
  TIE.act.vPlay = () => { if (V.playing) { vstop(); return vre(); } if (V.end) { V.end = false; V.line = 0; } V.playing = true; vplayFrom(V.line); };
  TIE.act.vLine = (i) => { vstop(); V.end = false; V.line = +i; V.dubState = ''; V.fb = null; vre(); const L = X().lines[+i]; if (!(V.dub && L.who === X().dub)) TIE.speech.say(L.en, { who: L.who }); };
  TIE.act.vNext = () => { const x = X(), was = V.playing || V.dubState === 'done'; vstop(); if (V.line >= x.lines.length - 1) return finishScene(); V.line++; V.dubState = ''; V.fb = null; if (was) { V.playing = true; vplayFrom(V.line); } else vre(); };
  TIE.act.vPrev = () => { vstop(); V.end = false; V.line = Math.max(0, V.line - 1); V.dubState = ''; V.fb = null; vre(); };
  TIE.act.vRepeat = () => { vstop(); const L = X().lines[V.line]; vre(); TIE.speech.say(L.en, { who: L.who, rate: .75 }); };
  TIE.act.vSubs = (k) => { V.subs = k; vre(); };
  TIE.act.vDubMode = () => { V.dub = !V.dub; V.dubState = ''; V.fb = null; vre(); };
  TIE.act.vRewind = () => { vstop(); V = vfresh(X(), V.dub); vre(); };
  TIE.act.vDub = async () => {
    const x = X(), L = x.lines[V.line];
    if (V.dubState === 'rec') { V.stopper && V.stopper(); return; } if (V.dubState === 'busy') return;
    let rec = null, heard = '', lis = null; if (TIE.speech.canRecord) { try { rec = await TIE.speech.record({ maxMs: 7000 }); } catch (e) { rec = null; } }
    if (!rec) TIE.app.toast('Sem microfone: a nota fica estimada.');
    TIE.sound.sfx.rec(); V.dubState = 'rec'; V.fb = null; vre();
    if (rec && TIE.speech.canListen) lis = TIE.speech.listen({ onInterim: (t) => { heard = t; }, onFinal: (t) => { heard = t; } });
    V.stopper = async () => { V.stopper = null; lis && lis.stop(); V.dubState = 'busy'; vre(); const out = rec ? await rec.stop() : { b64: '' }; const r = await TIE.ai.pronounce(out.b64, L.en, heard || (rec ? '' : L.en)); if (!V) return; V.fb = r; V.dubState = 'done'; const d = TIE.store.s.extras.dubs; d[x.id] = d[x.id] ? Math.round((d[x.id] + r.score) / 2) : r.score; TIE.store.save(); TIE.game.award('dub'); vre(); };
    setTimeout(() => V && V.dubState === 'rec' && V.stopper && V.stopper(), rec ? 5000 : 1600);
  };
  TIE.act.word = (w) => { const x = X(), clean = w.replace(/[.,!?;:“”"…]/g, ''); const all = x.vocab.concat(...D().EXTRAS.map((e) => e.vocab)); const hit = all.find(([en]) => en.toLowerCase().split(/\s+/).includes(clean.toLowerCase().replace(/’/g, '\'')) || en.toLowerCase() === clean.toLowerCase()); vstop(); V.word = { w: clean, meaning: hit ? hit[0] + ' = ' + hit[1] : '', line: x.lines[V.line] }; vre(); };
  TIE.act.wordClose = () => { V.word = null; vre(); };
  TIE.act.wordSave = () => { const x = X(), w = V.word, ok = addCard(w.line.en, w.line.pt, x.title + ' · ' + w.line.who); V.word = null; if (ok) { V.saved++; TIE.game.award('word'); TIE.app.toast('Levei para a Revisão: “' + w.line.en + '”'); } else TIE.app.toast('Essa fala já está na sua Revisão.'); vre(); };

  // Música: karaokê com lacunas
  let K = null, kaudio = null;
  const tracksOf = (k) => k.tracks.map((t) => t.ep ? Object.assign({}, t, { lines: D().EPS[t.ep].lyrics.map((l, i) => Object.assign({}, l, { gap: (D().EP_GAPS[t.ep] || [])[i] || l.en.split(' ')[0] })) }) : t);
  function kstop() { if (kaudio) { kaudio.pause(); kaudio = null; } TIE.sound.synth.stop(); if (K) { K.playing = false; clearInterval(K.timer); } }
  const gapOpts = (tr, i) => { const right = tr.lines[i].gap.replace(/[.,!?]/g, ''); const others = shuffle(tr.lines.map((l) => l.gap.replace(/[.,!?]/g, '')).filter((g) => g.toLowerCase() !== right.toLowerCase())).slice(0, 2); return shuffle([right].concat(others)); };
  TIE.screens.musica = {
    title: 'Música',
    render(p) {
      const k = D().ALBUMS.find((x) => x.id === p.id); if (!k) { setTimeout(() => TIE.router.replace('extra'), 0); return { html: '' }; }
      if (!K || K.id !== k.id) { kstop(); K = { id: k.id, tr: 0, line: -1, playing: false, gap: false, picks: {}, opts: {}, right: 0 }; }
      const tracks = tracksOf(k), tr = tracks[K.tr];
      const lyr = '<div class="lyrics">' + tr.lines.map((l, i) => { const on = i === K.line, g = l.gap.replace(/[.,!?]/g, ''), picked = K.picks[K.tr + '-' + i]; let en = esc(l.en); if (K.gap) { const re = new RegExp('\\b' + g.replace(/[’']/g, '.') + '\\b', 'i'); en = esc(l.en).replace(re, '<span class="gap' + (picked ? ' filled' : '') + '">' + (picked ? esc(picked) : '____') + '</span>'); } let opts = ''; if (K.gap && on && !picked) { const key = K.tr + '-' + i; K.opts[key] = K.opts[key] || gapOpts(tr, i); opts = '<div class="chips mt8">' + K.opts[key].map((o) => '<button class="chip" data-act="kGap" data-arg="' + esc(o) + '">' + esc(o) + '</button>').join('') + '</div>'; } return '<div class="lyric' + (on ? ' on' : '') + '" id="ly' + i + '"><div class="en">' + en + '</div><div class="pt">' + esc(l.pt) + '</div>' + opts + '</div>'; }).join('') + '</div>';
      return { theme: 'navy', html: '<div class="on-navy" style="display:flex;flex-direction:column;flex:1;min-height:0">' + C.topbar({ back: 'extra', kicker: 'EXTRA · Música · ' + k.level, title: k.title }) + '<div class="scroll"><div class="wrap stack" style="--wrap:760px;--gap:16px"><div class="card stack" style="--gap:14px"><div class="row" style="--gap:14px"><img src="' + k.img + '" alt="" style="width:96px;height:96px;border-radius:12px;object-fit:cover"><div class="grow"><div class="h2" style="color:#fff">' + esc(tr.title) + '</div><div class="xs">' + esc(tr.from) + (tr.audio ? ' · gravação do episódio' : ' · trilha sintetizada') + '</div></div></div><div class="controls"><button class="iconbtn" data-act="kTrack" data-arg="-1" aria-label="Anterior">' + I('back', 20) + '</button><button class="playbtn" data-act="kPlay" aria-label="Tocar">' + I(K.playing ? 'pause' : 'play', 24) + '</button><button class="iconbtn" data-act="kTrack" data-arg="1" aria-label="Próxima">' + I('next', 20) + '</button><span class="grow"></span><button class="chip' + (K.gap ? ' on' : '') + '" data-act="kGapMode"><span class="ck">' + (K.gap ? I('check', 12) : '') + '</span>Completar a letra</button></div></div>' + (K.gap ? '<div class="fb tip" style="background:var(--navy2);color:#fff">Uma palavra some em cada verso. Escolha antes do verso acabar. Acertos: <b>' + K.right + '</b> · +5 cada</div>' : '') + lyr + '<div class="stack" style="--gap:6px"><div class="lbl">Faixas</div>' + tracks.map((t, i) => '<button class="line' + (i === K.tr ? ' on' : '') + '" data-act="kSel" data-arg="' + i + '"><div class="who">FAIXA ' + (i + 1) + '</div><div class="en">' + esc(t.title) + '</div><div class="pt">' + esc(t.from) + '</div></button>').join('') + '</div></div></div></div>' };
    },
    after() { if (K && K.playing && K.line >= 0) { const el = document.getElementById('ly' + K.line); if (el) el.scrollIntoView({ block: 'center', behavior: 'smooth' }); } },
    leave() { kstop(); K = null; }
  };
  const kre = () => TIE.app.render();
  TIE.act.kPlay = () => { const k = D().ALBUMS.find((x) => x.id === K.id), tr = tracksOf(k)[K.tr]; if (K.playing) { kstop(); return kre(); } K.playing = true; K.line = 0; if (tr.audio) { kaudio = new Audio(tr.audio); kaudio.addEventListener('timeupdate', () => { if (!K) return; const n = Math.min(tr.lines.length - 1, Math.floor(kaudio.currentTime / (kaudio.duration || 1) * tr.lines.length)); if (n !== K.line) { K.line = n; kre(); } }); kaudio.addEventListener('ended', () => { if (K) { K.playing = false; TIE.game.award('song'); kre(); } }); kaudio.play().catch(() => {}); } else { const beat = 60 / (tr.bpm || 110) * 1000 * 8; TIE.sound.synth.play({ bpm: tr.bpm || 110, key: tr.key || 0 }); K.timer = setInterval(() => { if (!K) return; if (K.line >= tr.lines.length - 1) { kstop(); TIE.game.award('song'); } else K.line++; kre(); }, beat); } kre(); };
  TIE.act.kSel = (i) => { kstop(); K.tr = +i; K.line = -1; kre(); };
  TIE.act.kTrack = (d) => { const k = D().ALBUMS.find((x) => x.id === K.id); kstop(); K.tr = (K.tr + +d + k.tracks.length) % k.tracks.length; K.line = -1; kre(); };
  TIE.act.kGapMode = () => { K.gap = !K.gap; kre(); };
  TIE.act.kGap = (w) => { const k = D().ALBUMS.find((x) => x.id === K.id), tr = tracksOf(k)[K.tr], right = tr.lines[K.line].gap.replace(/[.,!?]/g, ''); const ok = w.toLowerCase() === right.toLowerCase(); K.picks[K.tr + '-' + K.line] = right; if (ok) { K.right++; TIE.game.award('ex_right'); } else { TIE.sound.sfx.soft(); TIE.app.toast('Era “' + right + '”. Segue o próximo verso.'); } kre(); };

  // Desafio relâmpago
  let G = null;
  const pool = (onlyId) => D().EXTRAS.filter((x) => x.lines.length && (!onlyId || x.id === onlyId)).flatMap((x) => x.lines.map((l) => ({ en: l.en, pt: l.pt })));
  function newQ() { const q = pick(G.pool.filter((l) => l.en !== (G.q && G.q.en))); const wrong = shuffle(G.all.filter((l) => l.pt !== q.pt)).slice(0, 2).map((l) => l.pt); G.q = q; G.opts = shuffle([q.pt].concat(wrong)); G.t0 = performance.now(); G.dur = Math.max(3200, 7000 - G.score * 12); }
  TIE.screens.desafio = {
    title: 'Desafio',
    render(p, q) {
      const s = TIE.store.s; if (!G) G = { state: 'idle', score: 0, combo: 1, left: 60, only: q.x || '', pool: [], all: pool(), hits: 0, miss: 0 };
      let inner = '';
      if (G.state !== 'play') inner = '<div class="wrap stack tc" style="--gap:16px;align-items:center;padding-top:28px">' + (G.state === 'over' ? '<div class="h1" style="color:#fff">Tempo esgotado.</div><div class="h2" style="color:#fff">' + G.score + ' pontos · ' + G.hits + ' acertos</div>' + (G.score >= s.extras.best && G.score > 0 ? '<span class="pill gold">Novo recorde</span>' : '') : '<div class="h1" style="color:#fff">Desafio relâmpago</div><p class="p" style="color:var(--onNavy);max-width:420px">As falas dos Extras caem na tela. Toque na tradução certa antes que a fala chegue ao chão. 60 segundos. Cada acerto vale mais com a sequência.</p>') + '<div class="sm">Recorde: ' + s.extras.best + '</div>' + C.btn(G.state === 'over' ? 'Jogar de novo' : 'Começar', { act: 'gStart', icon: 'game' }) + (G.only ? '<div class="xs">Só com as falas de ' + esc(byId(G.only).title) + '</div>' : '') + '</div>';
      else inner = '<div class="wrap stack" style="--gap:12px"><div class="row between"><span class="h2" style="color:#fff">' + G.score + ' pts</span><span class="pill or">x' + G.combo + '</span><span class="h2" style="color:#FFD27A" id="g-left">' + pad2(G.left) + 's</span></div><div class="quiz-field"><div class="faller" id="g-fall">' + esc(G.q.en) + '</div><div class="ground"></div></div><div class="stack" style="--gap:8px">' + G.opts.map((o, i) => '<button class="btn light" data-act="gPick" data-arg="' + i + '" style="justify-content:flex-start;text-align:left">' + esc(o) + '</button>').join('') + '</div></div>';
      return { theme: 'navy', html: '<div class="on-navy" style="display:flex;flex-direction:column;flex:1;min-height:0">' + C.topbar({ back: 'extra', kicker: 'EXTRA', title: 'Desafio relâmpago' }) + '<div class="scroll">' + inner + '</div></div>' };
    },
    after() { if (!G || G.state !== 'play') return; const el = document.getElementById('g-fall'); if (!el) return; cancelAnimationFrame(G.raf); const field = el.parentElement, H = field.clientHeight - el.offsetHeight - 6; const tick = () => { if (!G || G.state !== 'play') return; const k = Math.min(1, (performance.now() - G.t0) / G.dur); el.style.top = Math.round(k * H) + 'px'; if (k >= 1) { G.miss++; G.combo = 1; TIE.sound.sfx.soft(); newQ(); return TIE.app.render(); } G.raf = requestAnimationFrame(tick); }; G.raf = requestAnimationFrame(tick); },
    leave() { if (G) { clearInterval(G.clock); cancelAnimationFrame(G.raf); } G = null; }
  };
  TIE.act.gStart = () => { Object.assign(G, { state: 'play', score: 0, combo: 1, left: 60, hits: 0, miss: 0, pool: pool(G.only), q: null }); newQ(); clearInterval(G.clock); G.clock = setInterval(() => { if (!G) return; G.left--; const el = document.getElementById('g-left'); if (el) el.textContent = pad2(G.left) + 's'; if (G.left <= 0) { clearInterval(G.clock); cancelAnimationFrame(G.raf); G.state = 'over'; const s = TIE.store.s; if (G.score > s.extras.best) { s.extras.best = G.score; TIE.store.save(); } if (G.hits >= 5) TIE.game.award('ex_right'); TIE.sound.sfx.done(); TIE.app.render(); } }, 1000); TIE.app.render(); };
  TIE.act.gPick = (i) => { if (!G || G.state !== 'play') return; if (G.opts[+i] === G.q.pt) { G.score += 10 * G.combo; G.combo = Math.min(5, G.combo + 1); G.hits++; TIE.sound.sfx.ok(); } else { G.combo = 1; G.miss++; TIE.sound.sfx.soft(); TIE.app.toast(G.q.en + ' = ' + G.q.pt, 1800); } newQ(); TIE.app.render(); };
})();
