// Hoje: o curso em primeiro lugar (próxima etapa do episódio), depois o plano do dia, missões, Extra e Maggie.
(function () {
  const { esc } = TIE.u, C = TIE.C, I = TIE.icon;
  TIE.screens.inicio = {
    title: 'Hoje',
    render() {
      const s = TIE.store.s, p = s.profile, P = TIE.personalize.build(p), g = TIE.game.summary(), plan = TIE.guide.plan(), desk = TIE.app.isDesktop(), D = TIE.data;
      const hello = '<div class="row between top"><div><h1 class="h1">Oi, ' + esc(p.name) + '.</h1><div class="row mt8 wrapx" style="--gap:8px">' + C.levelpill() + '<span class="sm">Temporada ' + P.level.season + ' · ' + P.level.cefr + '</span></div></div>' + C.avatarBtn() + '</div>';
      const ep = plan.tasks.find((t) => t.k === 'ep'), cur = TIE.guide.current(), E = cur.ep, stepN = cur.step, st = D.STEPS[stepN - 1];
      const now = plan.now;
      const kick = ep && ep.done ? ' Episódio de hoje feito' : cur.started ? ' Continue o curso' : ' Comece o curso';
      const cta = ep && ep.done ? 'Seguir para a próxima etapa' : cur.started ? 'Continuar em ' + st.name : 'Começar o episódio ' + cur.num;
      const course = '<div class="now-card stack" style="--gap:12px"><div class="bgimg" style="background-image:url(assets/img/gen/bg/home.webp)"></div><div class="row between"><span class="kick">' + I('play', 12) + kick + '</span><span class="pill gold">+10 por etapa</span></div><div class="row" style="--gap:14px;align-items:flex-end"><span class="num" style="font-size:3rem;color:var(--orange);line-height:.85">' + TIE.u.pad2(cur.num) + '</span><div><div class="xs">Temporada 1 · E-book ' + E.ebook + '</div><div class="h1">' + esc(E.title) + '</div></div></div><div class="row" style="--gap:0">' + C.segs(stepN, stepN).replace('class="segs"', 'class="segs grow"') + '<span class="stepcount">' + stepN + '/10</span></div><div class="sm">' + (cur.started ? 'Você está em' : 'Primeira etapa:') + ' <b style="color:#fff">' + esc(st.name) + '</b> · cerca de 8 min para esta etapa</div>' + C.btn(cta, { go: 'episodio/' + cur.num, icon: 'play', cls: 'block' }) + '</div>';
      const planCard = '<div class="card stack" style="--gap:8px"><div class="row between"><div><div class="lbl">Plano de hoje</div><div class="h2 mt4">' + plan.tasks.filter((t) => t.done).length + ' de ' + plan.tasks.length + ' feitos · ' + plan.total + ' min</div></div>' + C.ring(g.goal.pct, g.goal.pct + '%') + '</div><div class="plan">' + plan.tasks.map((t, i) => '<a class="task' + (t.done ? ' done' : t === now ? ' now' : '') + '" href="#/' + t.go + '"><span class="n">' + (t.done ? I('check', 16) : i + 1) + '</span><span class="grow"><span class="h3" style="display:block;font-size:1rem">' + esc(t.t) + '</span><span class="xs">' + esc(t.sub) + '</span></span><span class="xs" style="font-weight:800;white-space:nowrap">' + t.min + ' min</span></a>').join('') + '</div><div class="xs">Meta de hoje: ' + g.goal.done + ' de ' + g.goal.target + ' pontos.' + (g.goal.hit ? ' Batida.' : '') + '</div></div>';
      const missions = '<div class="card stack" style="--gap:8px"><div class="row between"><div class="lbl">Missões do dia</div><span class="xs">' + g.missions.filter((m) => m.done).length + '/' + g.missions.length + '</span></div>' + C.missions(g.missions) + '</div>';
      const f = plan.focus;
      const focus = '<div class="card or stack" style="--gap:6px"><div class="lbl or">Foco da semana</div><div class="h2">' + esc(f.t) + '</div><p class="p">' + esc(f.b) + '</p><a class="btn link" href="#/' + f.go + '" style="justify-content:flex-start;--fg:var(--orangeD)"><span>' + esc(f.cta) + '</span>' + I('next', 18) + '</a></div>';
      const picks = P.extras.filter((x) => !x.locked).slice(0, desk ? 6 : 4);
      const extras = '<section class="stack" style="--gap:10px"><div class="row between"><div><div class="lbl or">EXTRA pra você</div><div class="h2 mt4">No seu nível e no seu gosto</div></div><a class="btn link" href="#/extra" style="white-space:nowrap">Ver tudo</a></div><div class="covers">' + picks.map((x) => C.cover(x)).join('') + '</div></section>';
      const m = P.missions[0];
      const maggie = '<a class="card row" href="#/maggie?modo=missao&m=' + m.k + '" style="--gap:14px"><span class="mic-pic">' + TIE.avatar.thumb(null, 64) + '</span><div class="grow"><div class="lbl">Mic · ' + esc(TIE.assist.cur().name) + ' · missão de hoje</div><div class="h3 mt4">' + esc(m.t) + '</div><div class="xs mt4">' + Math.round(s.maggie.secLeft / 60) + ' min de conversa no mês · +30 pontos</div></div>' + I('next', 20) + '</a>';
      const week = '<div class="card row" style="--gap:14px"><div class="row" style="--gap:6px">' + p.days.map((dd) => '<span style="width:12px;height:12px;border-radius:50%;background:' + (dd <= new Date().getDay() ? 'var(--blue)' : 'var(--line2)') + '"></span>').join('') + '</div><div class="p"><b>' + p.days.length + ' dias por semana</b>' + (() => { const R = TIE.personalize.reminders(p).map(TIE.personalize.hour); return R.length ? ' · lembrete' + (R.length > 1 ? 's' : '') + ' às ' + R.join(', ') : ''; })() + '</div></div>';
      const body = desk ? '<div class="home-grid"><div class="stack" style="--gap:16px">' + course + planCard + extras + '</div><div class="stack" style="--gap:16px">' + C.gamebar() + missions + maggie + focus + week + '</div></div>' : '<div class="stack" style="--gap:16px">' + C.gamebar() + course + planCard + missions + extras + maggie + focus + week + '</div>';
      return { tabs: true, html: (desk ? '' : '<header class="topbar">' + C.logo({ size: 16 }) + '<span class="grow"></span>' + C.demoBadge() + '</header>') + '<div class="scroll"><div class="wrap stack" style="--wrap:1120px;--gap:16px">' + hello + body + '</div></div>' };
    }
  };
})();
