// Mic: conversa com o assistente escolhido (Maggie, Robert, Becky, Zach ou Barbara; ver js/data/assistants.js),
// com avatar, voz, quatro modos, retorno a cada fala e relatório no fim. A rota continua #/maggie.
(function () {
  const { esc, sub, fmt, uid } = TIE.u, C = TIE.C, I = TIE.icon, D = () => TIE.data;
  let M = null, av = null, listener = null, clock = 0;
  const S = () => TIE.store.s, PZ = () => TIE.personalize.build(S().profile), AS = () => TIE.assist.cur();
  function newSession(q) { const P = PZ(); const mode = ['livre', 'missao', 'pronuncia', 'extra'].includes(q.modo) ? q.modo : 'missao'; return { stage: 'lobby', mode, mission: q.m || P.missions[0].k, extraId: q.x || S().extras.lastId || 'woods-and-beans', turns: [], turn: 0, busy: false, listening: false, interim: '', subsPt: true, hands: false, secStart: 0, last: null, pronIdx: 0, pronState: 'idle', ended: false, speaking: false }; }
  const sessFor = () => ({ mode: M.mode, mission: M.mission, extraId: M.extraId, ctx: PZ().ctx, turns: M.turns, turn: M.turn, name: S().profile.name, ctxFormats: S().profile.formats, persona: AS().persona, aName: AS().name, aThe: TIE.assist.the() });
  function stopListening() { if (listener) { listener.stop(); listener = null; } if (M) { M.listening = false; M.interim = ''; } av && av.listening(false); }
  function hangup() { stopListening(); TIE.speech.stop(); clearInterval(clock); if (av) { av.talking(false); av.mouth('rest'); } }
  function maggieSays(en, opt) { if (!M) return Promise.resolve(); M.speaking = true; av && av.talking(true); return TIE.speech.say(en, Object.assign({ who: AS().name, mouth: (v) => av && av.mouth(v) }, opt)).then(() => { if (!M) return; M.speaking = false; av && av.talking(false); if (M.hands && M.stage === 'call' && !M.ended && M.mode !== 'pronuncia') startListening(); }); }

  function stage() { const last = M.turns.filter((t) => t.who === 'her').slice(-1)[0], on = M.stage === 'call'; return C.stage({ id: 'av-live', status: on ? (M.listening ? 'Ouvindo você' : M.busy ? 'Pensando' : 'Ao vivo') : AS().full, listening: M.listening, caption: on && last ? '<div class="caption"><span class="en">' + esc(last.en) + '</span>' + (M.subsPt ? '<span class="ptl"><span>' + esc(last.pt) + '</span></span>' : '') + '</div>' : '' }); }
  function lobby() {
    const P = PZ(), s = S();
    const modes = '<div class="modes">' + D().MAGGIE.MODES.map((m) => '<button class="mode' + (M.mode === m.k ? ' on' : '') + '" data-act="mgMode" data-arg="' + m.k + '">' + I(m.icon, 22, 'style="color:#FFD27A"') + '<span class="h3">' + m.t + '</span><span class="xs">' + m.s + '</span></button>').join('') + '</div>';
    let pickRow = '';
    if (M.mode === 'missao') { const keys = Object.keys(D().MAGGIE.MISSIONS), mine = P.missions.map((m) => m.k), order = mine.concat(keys.filter((k) => !mine.includes(k))); pickRow = '<div class="stack" style="--gap:8px"><div class="lbl">Escolha a cena</div><div class="chips">' + order.map((k) => C.chip(D().MAGGIE.MISSIONS[k].t + (mine.includes(k) ? ' · seu objetivo' : ''), { on: M.mission === k, act: 'mgMission', arg: k })).join('') + '</div><div class="card" style="padding:14px"><div class="xs">' + TIE.assist.The() + ' faz o papel de ' + esc(D().MAGGIE.MISSIONS[M.mission].role) + '.</div><div class="h3 mt4" style="color:#fff">' + esc(D().MAGGIE.MISSIONS[M.mission].goal) + '</div></div></div>'; }
    if (M.mode === 'extra') pickRow = '<div class="stack" style="--gap:8px"><div class="lbl">Qual Extra você viu?</div><div class="chips">' + D().EXTRAS.filter((x) => !x.locked).map((x) => C.chip(x.title + (S().extras.seen[x.id] ? ' · visto' : ''), { on: M.extraId === x.id, act: 'mgExtra', arg: x.id })).join('') + '</div></div>';
    if (M.mode === 'livre') pickRow = '<div class="xs">' + TIE.assist.The() + ' puxa assunto a partir do que você curte: ' + esc(P.ctx.formats.concat(P.ctx.genres).slice(0, 5).join(', ') || 'o seu dia') + '.</div>';
    if (M.mode === 'pronuncia') pickRow = '<div class="xs">Seis frases com os sons que mais travam quem fala português.</div>';
    const A = AS(), who = '<div class="stack" style="--gap:8px"><div class="lbl">Seu assistente</div>' + C.assistPicker('mgPick') + '<div class="xs"><b style="color:#fff">' + esc(A.full) + '</b> · ' + esc(A.role) + '. ' + esc(A.style) + '</div></div>';
    return '<div class="stack" style="--gap:16px">' + who + modes + pickRow + C.btn('Começar a conversa · +30 pontos', { act: 'mgCall', icon: 'mic', cls: 'block' }) + '<div class="row wrapx" style="--gap:8px">' + C.demoBadge() + '<span class="xs">' + Math.round(s.maggie.secLeft / 60) + ' de 60 min restantes no mês' + (P.defaults.training ? ' · modo treino, sem nota' : '') + '</span></div>' + (!TIE.speech.canListen ? '<div class="fb tip">Este navegador não reconhece fala. Você pode conversar digitando. Para falar, use o Chrome ou o Edge.</div>' : '') + '</div>';
  }
  function fbChips(t) { const f = t.fb; if (!f) return ''; const head = f.status === 'certo' ? I('check', 18) + '<span><b>Certo.</b> ' + esc(f.explain_pt || '') + '</span>' : f.status === 'ajuste' ? I('pen', 18) + '<span><b>Ajuste</b>' + (f.corrected ? '<span class="fix-line">' + esc(f.corrected) + '</span>' : '') + esc(f.explain_pt || '') + (f.tip_pt ? ' ' + esc(f.tip_pt) : '') + '</span>' : I('bulb', 18) + '<span><b>Mais natural</b>' + (f.corrected ? '<span class="fix-line">' + esc(f.corrected) + '</span>' : '') + esc(f.explain_pt || '') + '</span>'; return '<div class="fbrow"><div class="fbchip ' + f.status + '">' + head + '</div>' + (t.pron || []).map((p) => '<div class="fbchip natural">' + I('wave', 18) + '<span><b>' + esc(p.word) + '</b> · ' + esc(p.tip_pt) + '</span></div>').join('') + '</div>'; }
  function transcript() { return '<div class="transcript" id="mg-tr">' + M.turns.map((t, i) => { if (t.who === 'coach') return '<div class="card paper" style="align-self:stretch"><div class="lbl or">Coach · em português</div><p class="p mt4">' + t.html + '</p></div>'; if (t.who === 'her') return '<div class="bub her"><div class="en">' + esc(t.en) + '</div>' + (M.subsPt ? '<div class="pt">' + esc(t.pt) + '</div>' : '') + ((t.words || []).length ? '<div class="row wrapx mt8" style="--gap:6px">' + t.words.map((w) => '<button class="pill bl" data-act="mgWord" data-arg="' + i + ':' + esc(w.en) + '">' + I('plus', 12) + esc(w.en) + ' · ' + esc(w.pt) + '</button>').join('') + '</div>' : '') + '</div>'; return '<div class="bub me"><div class="en">' + esc(t.en) + '</div></div>' + fbChips(t); }).join('') + (M.listening ? '<div class="bub me interim"><div class="en" id="mg-interim">' + esc(M.interim || 'Ouvindo…') + '</div></div>' : '') + (M.busy ? '<div class="thinking"><i></i><i></i><i></i></div>' : '') + (M.ended ? '<div class="card paper stack pop" style="--gap:10px;align-self:stretch"><div class="lbl or">A cena terminou</div><div class="h3">Veja o que foi bem e o que ajustar.</div>' + C.btn('Ver o relatório', { act: 'mgEnd', icon: 'star', cls: 'block' }) + '</div>' : '') + '</div>'; }
  function dock() { const hint = M.last && M.last.hint_en; return '<div class="dock"><div class="help">' + D().MAGGIE.HELP.map((h) => '<button data-act="mgHelp" data-arg="' + esc(h.en) + '">' + esc(h.en) + ' <small>' + esc(h.pt) + '</small></button>').join('') + '<button data-act="mgCoach">' + I('book', 16) + ' Me explica em português</button>' + (hint ? '<button data-act="mgHint">' + I('bulb', 16) + ' Dica</button>' : '') + '<button data-act="mgSubs">' + I('cc', 16) + (M.subsPt ? ' Esconder PT' : ' Mostrar PT') + '</button><button data-act="mgHands">' + I('mic', 16) + (M.hands ? ' Mãos livres: sim' : ' Mãos livres: não') + '</button></div><div class="say"><input class="input" id="mg-input" placeholder="' + (TIE.speech.canListen ? 'Fale no microfone ou digite' : 'Digite a sua resposta em inglês') + '" autocomplete="off" data-ui="mgTyped" data-enter="mgSend"' + (M.busy || M.ended ? ' disabled' : '') + '><button class="iconbtn" data-act="mgSend" aria-label="Enviar" style="width:52px;height:52px">' + I('send', 22) + '</button><button class="mic' + (M.listening ? ' rec' : '') + '" data-act="mgMic" aria-label="' + (M.listening ? 'Parar' : 'Falar') + '"' + (M.busy || M.ended ? ' disabled style="opacity:.5"' : '') + '>' + I(M.listening ? 'stop' : 'mic', 28) + '</button></div></div>'; }
  function pronPanel() { const list = D().MAGGIE.PRON, it = list[M.pronIdx], r = M.pronRes, training = PZ().defaults.training; return '<div class="stack" style="--gap:14px;padding:16px"><div class="card paper stack tc" style="--gap:12px;align-items:center"><div class="lbl">Frase ' + (M.pronIdx + 1) + ' de ' + list.length + '</div><div class="h1">' + esc(it.en) + '</div><div class="fb tip" style="text-align:left;width:100%"><b>Dica ' + TIE.assist.of() + ':</b> ' + esc(it.tip) + '</div><div class="row center" style="--gap:10px">' + C.btn('Ouvir', { kind: 'ghost compact', act: 'mgPronHear', icon: 'speaker' }) + '<button class="mic' + (M.pronState === 'rec' ? ' rec' : '') + '" data-act="mgPronRec" aria-label="Gravar">' + I(M.pronState === 'rec' ? 'stop' : 'mic', 28) + '</button></div><div class="sm" style="font-weight:700">' + (M.pronState === 'rec' ? 'Ouvindo… toque para parar' : M.pronState === 'busy' ? TIE.assist.The() + ' está ouvindo…' : 'Toque no microfone e diga a frase') + '</div>' + (r ? '<div class="stack pop" style="--gap:10px;width:100%">' + (training ? '' : '<div class="row center base" style="--gap:4px"><span class="num" style="font-size:3rem">' + r.score + '</span><span class="h3 muted">/10</span></div>') + '<div class="fb ' + (r.score >= 8 ? 'ok' : 'fix') + '" style="text-align:left"><b>' + esc(r.praise_pt) + '</b>' + (r.heard ? '<br><span class="sm">Entendi: “' + esc(r.heard) + '”</span>' : '') + (r.issues || []).map((x) => '<br><b>' + esc(x.word) + ':</b> ' + esc(x.issue_pt ? x.issue_pt + ' ' : '') + esc(x.tip_pt)).join('') + '</div></div>' : '') + '</div><div class="row" style="--gap:10px">' + C.btn('Anterior', { kind: 'ghost compact', act: 'mgPronNav', arg: '-1', cls: 'grow' }) + C.btn(M.pronIdx < list.length - 1 ? 'Próxima frase' : 'Encerrar', { act: M.pronIdx < list.length - 1 ? 'mgPronNav' : 'mgEnd', arg: '1', cls: 'grow', kind: 'compact' }) + '</div></div>'; }

  TIE.screens.maggie = {
    title: 'Mic',
    render(p, q) {
      if (!M || (M.stage === 'lobby' && (q.modo || q.m || q.x) && M.q !== JSON.stringify(q))) { hangup(); M = newSession(q); M.q = JSON.stringify(q); }
      const desk = TIE.app.isDesktop(), inCall = M.stage === 'call';
      const top = '<header class="topbar"><button class="iconbtn" data-act="' + (inCall ? 'mgEnd' : 'mgBack') + '" aria-label="' + (inCall ? 'Encerrar' : 'Voltar') + '">' + I(inCall ? 'close' : 'back', 20) + '</button><div class="ttl"><div class="lbl">' + (inCall ? (M.mode === 'missao' ? 'Missão · ' + D().MAGGIE.MISSIONS[M.mission].t : D().MAGGIE.MODES.find((m) => m.k === M.mode).t) : 'Conversa em tempo real') + '</div><div class="h2" style="color:#fff;margin-top:2px">' + esc(AS().name) + '</div></div>' + (inCall ? '<span class="pill" style="background:var(--navy2);color:#FFD27A">' + Math.max(0, Math.round((S().maggie.secLeft - (Date.now() - M.secStart) / 1000) / 60)) + ' min</span>' + C.btn('Encerrar', { kind: 'compact', act: 'mgEnd' }) : C.demoBadge()) + '</header>';
      const talk = M.mode === 'pronuncia' ? pronPanel() : transcript() + dock();
      let body;
      if (desk) body = '<div class="live-grid"><div class="left stack" style="--gap:16px">' + stage() + (inCall ? '<div class="xs">A legenda mostra a última fala ' + TIE.assist.of() + '. Toque nas palavras azuis para levar para a Revisão.</div>' : lobby()) + '</div><div class="right">' + (inCall ? talk : '<div class="transcript"><div class="card"><div class="h3" style="color:#fff">Como funciona</div><div class="stack mt8" style="--gap:8px">' + [TIE.assist.The() + ' fala em inglês, no seu nível. A legenda em português pode ficar ligada.', 'Responda falando no microfone ou digitando.', 'Cada fala sua recebe retorno: certo, ajuste (em azul) ou mais natural.', 'No fim, o relatório mostra o que foi bem, o que ajustar e as palavras novas.'].map((t, i) => '<div class="row top" style="--gap:10px"><span class="num" style="color:var(--orange);width:18px">' + (i + 1) + '</span><span class="sm" style="color:#fff">' + t + '</span></div>').join('') + '</div></div></div>') + '</div></div>';
      else body = '<div style="padding:0 16px 12px">' + stage() + '</div>' + (inCall ? talk : '<div class="wrap">' + lobby() + '</div>');
      return { theme: 'navy', tabs: !inCall, nav: 'maggie', html: '<div class="live on-navy" style="flex:1;min-height:0;display:flex;flex-direction:column">' + top + (desk ? body : '<div class="scroll" id="mg-scroll">' + body + '</div>') + '</div>' };
    },
    after() { if (av) av.destroy(); av = TIE.avatar.mount(document.getElementById('av-live')); if (M && M.speaking) av.talking(true); if (M && M.last) av.mood(M.last.mood || 'happy'); if (M && M.listening) av.listening(true); const sc = document.getElementById('mg-scroll') || document.getElementById('mg-tr'); if (sc && M && M.stage === 'call') sc.scrollTop = sc.scrollHeight; },
    leave() { hangup(); if (av) av.destroy(); av = null; if (M && M.stage === 'call' && M.turns.length > 1) finish(); M = null; }
  };
  const re = () => TIE.app.render();
  TIE.act.mgBack = () => { history.length > 1 ? history.back() : TIE.router.go('inicio'); };
  // Troca de assistente (vale para as próximas conversas): o personagem se apresenta com a fala dele no episódio 1.
  TIE.act.mgPick = (k) => { if (!M || M.stage !== 'lobby') return; TIE.store.s.profile.assistant = TIE.assist.get(k).k; TIE.store.save(); TIE.speech.stop(); re(); setTimeout(() => M && maggieSays(AS().hello.en), 300); };
  TIE.act.mgMode = (k) => { M.mode = k; re(); }; TIE.act.mgMission = (k) => { M.mission = k; re(); }; TIE.act.mgExtra = (k) => { M.extraId = k; re(); };
  TIE.act.mgSubs = () => { M.subsPt = !M.subsPt; re(); };
  TIE.act.mgHands = () => { M.hands = !M.hands; TIE.app.toast(M.hands ? 'Mãos livres: depois de cada fala ' + TIE.assist.of() + ' o microfone liga sozinho.' : 'Mãos livres desligado.'); re(); };
  TIE.act.mgCall = () => {
    M.stage = 'call'; M.secStart = Date.now(); M.turns = []; M.turn = 0;
    clearInterval(clock); clock = setInterval(() => { if (!M) return; const el = document.querySelector('.topbar .pill'); if (el) el.textContent = Math.max(0, Math.round((S().maggie.secLeft - (Date.now() - M.secStart) / 1000) / 60)) + ' min'; }, 15000);
    if (M.mode === 'pronuncia') { M.pronIdx = 0; M.pronRes = null; re(); setTimeout(() => maggieSays('Hi, ' + S().profile.name + '. Let’s practice some tricky sounds. Listen first, then say it.'), 500); return; }
    const o = TIE.ai.opener(sessFor()); M.turns.push({ who: 'her', en: o.reply_en, pt: o.reply_pt, words: (o.words || []).map(([en, pt]) => ({ en, pt })) }); const h = TIE.ai.hint(o.reply_en); M.last = { mood: 'happy', hint_en: h.en, hint_pt: h.pt }; re(); setTimeout(() => maggieSays(o.reply_en), 500);
  };
  function startListening() {
    if (!TIE.speech.canListen) { TIE.app.toast('Este navegador não reconhece fala. Digite a resposta.'); const el = document.getElementById('mg-input'); el && el.focus(); return; }
    TIE.speech.stop(); av && av.talking(false); M.speaking = false; M.listening = true; M.interim = ''; TIE.sound.sfx.rec(); av && av.listening(true); re();
    listener = TIE.speech.listen({ onInterim: (t) => { if (!M) return; M.interim = t; const el = document.getElementById('mg-interim'); if (el) el.textContent = t; }, onFinal: (t) => { if (M) { stopListening(); send(t); } }, onEnd: (t) => { if (M && M.listening) { stopListening(); if (!t) TIE.app.toast('Não ouvi nada. Toque no microfone e fale perto do aparelho.'); re(); } }, onError: (e) => { if (!M) return; stopListening(); if (e === 'not-allowed' || e === 'service-not-allowed') TIE.app.toast('O microfone está bloqueado. Libere nas permissões do navegador ou digite.'); else if (e !== 'no-speech' && e !== 'aborted') TIE.app.toast('O reconhecimento de fala falhou (' + e + '). Digite a resposta.'); re(); } });
  }
  TIE.act.mgMic = () => { if (!M || M.busy || M.ended) return; if (M.listening) { stopListening(); re(); return; } startListening(); };
  TIE.act.mgSend = () => { const t = (TIE.ui.mgTyped || '').trim(); if (!t || M.busy || M.ended) return; TIE.ui.mgTyped = ''; send(t); };
  async function send(text) {
    if (!M || M.stage !== 'call') return;
    const me = { who: 'me', en: text }; M.turns.push(me); M.busy = true; av && av.mood('thinking'); re();
    const r = await TIE.ai.tutor(sessFor(), text); if (!M) return;
    me.fb = r.feedback; me.pron = r.pron_watch || []; M.turn++; M.busy = false; M.last = r;
    TIE.game.award('maggie_turn', { sec: 20 });
    M.turns.push({ who: 'her', en: r.reply_en, pt: r.reply_pt, words: r.new_words || [] });
    av && av.mood(r.mood || 'happy'); if (r.end || M.turn >= 9) M.ended = true; re(); maggieSays(r.reply_en);
  }
  TIE.act.mgHelp = (en) => { const h = D().MAGGIE.HELP.find((x) => x.en === en), last = M.turns.filter((t) => t.who === 'her').slice(-1)[0]; if (!last || M.busy) return; M.turns.push({ who: 'me', en: h.en }); M.turns.push({ who: 'her', en: last.en, pt: last.pt, words: [] }); re(); maggieSays(last.en, { rate: en === 'Slowly, please.' ? .7 : .85 }); };
  TIE.act.mgCoach = () => { const last = M.turns.filter((t) => t.who === 'her').slice(-1)[0]; if (!last) return; const h = M.last && M.last.hint_en ? M.last : TIE.ai.hint(last.en); M.turns.push({ who: 'coach', html: TIE.assist.The() + ' disse: <b>' + esc(last.pt) + '</b><br>Você pode responder: <b>' + esc(h.hint_en || h.en) + '</b> <span class="sm">(' + esc(h.hint_pt || h.pt) + ')</span>' }); re(); };
  TIE.act.mgHint = () => { const h = M.last; if (!h || !h.hint_en) return; const el = document.getElementById('mg-input'); if (el) { el.value = h.hint_en; TIE.ui.mgTyped = h.hint_en; el.focus(); } TIE.app.toast('Dica: ' + h.hint_pt); };
  TIE.act.mgWord = (arg) => { const i = arg.slice(0, arg.indexOf(':')), en = arg.slice(arg.indexOf(':') + 1); const w = (M.turns[+i].words || []).find((x) => x.en === en); if (w && TIE.addCard(w.en, w.pt, 'Mic · ' + AS().name)) { TIE.game.award('word'); TIE.app.toast('Levei “' + w.en + '” para a Revisão.'); } else TIE.app.toast('Já está na sua Revisão.'); };
  TIE.act.mgPronHear = () => maggieSays(D().MAGGIE.PRON[M.pronIdx].en, { rate: .85 });
  TIE.act.mgPronNav = (d) => { const n = D().MAGGIE.PRON.length; M.pronIdx = Math.max(0, Math.min(n - 1, M.pronIdx + +d)); M.pronRes = null; M.pronState = 'idle'; re(); maggieSays(D().MAGGIE.PRON[M.pronIdx].en, { rate: .85 }); };
  TIE.act.mgPronRec = async () => {
    const it = D().MAGGIE.PRON[M.pronIdx]; if (M.pronState === 'rec') { M.stopper && M.stopper(); return; } if (M.pronState === 'busy') return;
    let rec = null, heard = '', lis = null; if (TIE.speech.canRecord) { try { rec = await TIE.speech.record({ maxMs: 7000 }); } catch (e) { rec = null; } }
    if (!rec) TIE.app.toast('Sem microfone: a nota fica estimada.');
    TIE.speech.stop(); TIE.sound.sfx.rec(); M.pronState = 'rec'; M.pronRes = null; av && av.listening(true); re();
    if (rec && TIE.speech.canListen) lis = TIE.speech.listen({ onInterim: (t) => { heard = t; }, onFinal: (t) => { heard = t; } });
    M.stopper = async () => { M.stopper = null; lis && lis.stop(); M.pronState = 'busy'; av && av.listening(false); re(); const out = rec ? await rec.stop() : { b64: '' }; const r = await TIE.ai.pronounce(out.b64, it.en, heard); if (!M) return; M.pronRes = r; M.pronState = 'idle'; M.turns.push({ who: 'me', en: r.heard || heard || it.en, fb: { status: r.score >= 8 ? 'certo' : 'ajuste', original: r.heard || '', corrected: r.score >= 8 ? '' : it.en, explain_pt: r.praise_pt, cat: 'Pronúncia' }, pron: (r.issues || []).map((x) => ({ word: x.word, tip_pt: x.tip_pt })) }); TIE.game.award(r.score >= 8 ? 'mic_good' : 'mic_try', { sec: 15 }); re(); };
    setTimeout(() => M && M.pronState === 'rec' && M.stopper && M.stopper(), rec ? 5000 : 1500);
  };
  function finish() { const secs = M.secStart ? Math.round((Date.now() - M.secStart) / 1000) : 0; const sess = { id: uid(), at: Date.now(), assistant: AS().k, mode: M.mode, mission: M.mission, extraId: M.extraId, secs, turns: M.turns.filter((t) => t.who !== 'coach').map((t) => ({ who: t.who, en: t.en, pt: t.pt || '', fb: t.fb || null, pron: t.pron || [], words: t.words || [] })), report: null }; const s = S(); s.maggie.sessions = [sess].concat(s.maggie.sessions).slice(0, 12); s.maggie.secLeft = Math.max(0, s.maggie.secLeft - secs); TIE.store.save(); if (sess.turns.filter((t) => t.who === 'me').length >= 2) TIE.game.award('maggie_session'); return sess; }
  TIE.act.mgEnd = () => { if (!M || M.stage !== 'call') return; hangup(); const sess = finish(); M = null; TIE.router.go('maggie/relatorio/' + sess.id); };

  TIE.screens.relatorio = {
    title: 'Relatório',
    render(p) {
      const s = S(), sess = s.maggie.sessions.find((x) => x.id === p.id) || s.maggie.sessions[0]; if (!sess) { setTimeout(() => TIE.router.replace('maggie'), 0); return { html: '' }; }
      const R = sess.report, title = sess.mode === 'missao' ? D().MAGGIE.MISSIONS[sess.mission].t : D().MAGGIE.MODES.find((m) => m.k === sess.mode).t, mine = sess.turns.filter((t) => t.who === 'me'), ok = mine.filter((t) => t.fb && t.fb.status === 'certo').length;
      const head = '<div class="now-card stack" style="--gap:10px"><span class="kick">' + I('star', 12) + ' Relatório</span><div class="h1" style="color:#fff">' + esc(title) + '</div><div class="sm" style="color:var(--onNavy)">' + fmt(sess.secs) + ' de conversa · ' + mine.length + ' falas suas · +30 pontos</div>' + (R ? '<p class="p" style="color:#fff">' + esc(R.summary_pt) + '</p>' : '') + '</div>';
      if (!R) return { tabs: true, nav: 'maggie', html: C.topbar({ back: 'maggie', kicker: 'Mic', title: 'Relatório' }) + '<div class="scroll"><div class="wrap stack" style="--wrap:760px">' + head + '<div class="card row" style="--gap:12px"><div class="thinking" style="background:var(--cream)"><i></i><i></i><i></i></div><span class="p">' + TIE.assist.The(TIE.assist.get(sess.assistant)) + ' está escrevendo o seu relatório…</span></div></div></div>' };
      const training = PZ().defaults.training, words = R.words || [];
      return { tabs: true, nav: 'maggie', html: C.topbar({ back: 'maggie', kicker: 'Mic', title: 'Relatório', right: '<span class="demo-badge' + (R.source === 'ia' ? ' live' : '') + '"><i></i>' + (R.source === 'ia' ? 'Feito pela IA' : 'Modo demo') + '</span>' }) + '<div class="scroll"><div class="wrap stack" style="--wrap:760px;--gap:16px">' + head + (training ? '' : '<div class="grid2"><div class="stat"><div class="num">' + ok + '/' + mine.length + '</div><div class="sm mt8">falas certas de primeira</div></div><div class="stat"><div class="num">' + words.length + '</div><div class="sm mt8">expressões novas</div></div></div>') +
        '<div class="card stack" style="--gap:10px"><div class="lbl gr">O que foi bem</div>' + (R.strengths || []).map((t) => '<div class="row top" style="--gap:10px">' + I('check', 20, 'style="color:var(--green);flex:none;margin-top:2px"') + '<span class="p">' + esc(t) + '</span></div>').join('') + '</div>' +
        ((R.fixes || []).length ? '<div class="stack" style="--gap:8px"><div class="lbl bl">O que ajustar</div>' + R.fixes.map((f) => '<div class="card stack" style="--gap:8px"><div class="cmp"><span class="k" style="color:var(--muted)">VOCÊ</span><span class="p strike">' + esc(f.said) + '</span><span class="k" style="color:var(--blue)">MELHOR</span><button class="en" data-act="say" data-arg="' + esc(f.better) + '" style="text-align:left;font-size:1.06rem">' + esc(f.better) + ' ' + I('speaker', 16, 'style="vertical-align:-2px;color:var(--blue)"') + '</button></div><div class="fb fix">' + (f.cat ? '<b>' + esc(f.cat) + '.</b> ' : '') + esc(f.why_pt) + '</div></div>').join('') + '</div>' : '') +
        ((R.pron || []).length ? '<div class="card stack" style="--gap:10px"><div class="lbl">Pronúncia para ficar de olho</div>' + R.pron.map((x) => '<div class="row top" style="--gap:10px"><button class="pill navy" data-act="say" data-arg="' + esc(x.word) + '">' + I('play', 12) + esc(x.word) + '</button><span class="p">' + esc(x.tip_pt) + '</span></div>').join('') + '</div>' : '') +
        (words.length ? '<div class="card stack" style="--gap:10px"><div class="lbl or">Palavras novas</div><div class="chips">' + words.map((w) => '<span class="pill" style="font-size:.95rem;padding:7px 12px"><b>' + esc(w.en) + '</b>&nbsp;· ' + esc(w.pt) + '</span>').join('') + '</div>' + C.btn('Levar ' + words.length + ' para a Revisão', { act: 'repSave', arg: sess.id, icon: 'plus', kind: 'blue' }) + '</div>' : '') +
        '<div class="card or stack" style="--gap:6px"><div class="lbl or">Próxima meta</div><p class="p">' + esc(R.next_goal_pt) + '</p></div><div class="row wrapx" style="--gap:8px">' + C.btn('Conversar de novo', { go: 'maggie?modo=' + sess.mode + (sess.mode === 'missao' ? '&m=' + sess.mission : '') + '&r=' + Date.now(), icon: 'mic' }) + C.btn('Voltar para Hoje', { kind: 'ghost', go: 'inicio' }) + '</div></div></div>' };
    },
    async after(root, p) { const s = S(), sess = s.maggie.sessions.find((x) => x.id === p.id) || s.maggie.sessions[0]; if (!sess || sess.report || sess.loading) return; sess.loading = true; const R = await TIE.ai.report({ ctx: PZ().ctx, mode: sess.mode, mission: sess.mission, turns: sess.turns, aName: TIE.assist.get(sess.assistant).name, aThe: TIE.assist.the(TIE.assist.get(sess.assistant)) }); sess.report = R; delete sess.loading; TIE.store.save(); if (TIE.router.parse().name === 'relatorio') TIE.app.render(); }
  };
  TIE.act.repSave = (id) => { const sess = S().maggie.sessions.find((x) => x.id === id); let n = 0; (sess.report.words || []).forEach((w) => { if (TIE.addCard(w.en, w.pt, 'Mic · ' + TIE.assist.get(sess.assistant).name)) n++; }); if (n) TIE.game.award('word'); TIE.app.toast(n ? n + (n > 1 ? ' cartões novos' : ' cartão novo') + ' na Revisão.' : 'Essas palavras já estavam na Revisão.'); TIE.app.render(); };
})();
