// Player do episódio: as 10 etapas do v3.2. Cada etapa concluída dá pontos; o Take the Mic grava e avalia.
(function () {
  const { esc, pad2, fmt } = TIE.u, C = TIE.C, I = TIE.icon, D = () => TIE.data;
  let P = null, audio = null;
  const fresh = (ep, step) => ({ ep, step, line: 0, playing: false, micIdx: 0, mic: 'idle', exIdx: 0, itIdx: null, trans: true, speed: TIE.store.s.settings.slow ? .75 : 1, sheet: false, dl: 'idle', aT: 0, aD: 0, showScore: false, fb: null });
  function stopAll() { if (audio) { audio.pause(); audio = null; } TIE.sound.synth.stop(); TIE.speech.stop(); if (P) { P.playing = false; clearInterval(P.timer); } }
  const stepAudio = (E, step) => (step === 1 ? E.introAudio : step === 2 || step === 10 ? E.songAudio : '');
  const E = () => D().EPS[P.ep];
  const re = () => TIE.app.render();
  const playIco = () => I(P.playing ? 'pause' : 'play', 20);
  // O que falta fazer na etapa antes de liberar a próxima ('' = liberada). Etapa já ultrapassada ou episódio concluído
  // ficam liberados. Leitura (Take a Lesson, Take Away) e cena sem vídeo não pedem ação.
  function need(Ep, s, step) {
    if (step === 3) return s.ebooks[Ep.ebook] ? '' : 'Baixe o e-book para seguir';
    if (s.epsDone[Ep.num] || (s.prog[Ep.num] || 1) > step || s.stepOk[Ep.num + '-' + step]) return '';
    if (step === 1) return 'Ouça a abertura até o fim';
    if (step === 2) return 'Ouça a música até o fim';
    if (step === 4) return Ep.sceneVideo ? 'Assista à cena até o fim' : '';
    if (step === 5) return 'Ouça o diálogo até o fim';
    if (step === 6) { const left = Ep.mic.filter((_, i) => s.scores[Ep.num + '-' + i] == null).length; return !left ? '' : left === 1 ? 'Falta gravar 1 frase' : 'Faltam ' + left + ' frases para gravar'; }
    if (step === 9) { const left = Ep.ex.reduce((a, ex, x) => a + ex.items.filter((_, j) => s.exAns[Ep.num + '-' + x + '-' + j] == null).length, 0); return !left ? '' : left === 1 ? 'Falta 1 resposta' : 'Faltam ' + left + ' respostas'; }
    if (step === 10) return 'Cante a música até o fim';
    return '';
  }
  // Modo teste (botão "Etapas livres" no canto da tela): o Avançar ignora o que falta fazer.
  const gate = (Ep, s, step) => (s.settings.free ? '' : need(Ep, s, step));
  const mark = (step) => { const s = TIE.store.s, k = P && P.ep + '-' + step; if (!P || s.stepOk[k]) return; s.stepOk[k] = true; TIE.store.save(); TIE.sound.sfx.ok(); };

  function head(Ep, s) { const cur = D().STEPS[P.step - 1]; return '<div class="player-head"><div class="row" style="--gap:10px"><button class="iconbtn" data-act="plClose" aria-label="Fechar">' + I('close', 20) + '</button><div class="grow tc"><div class="lbl" style="font-size:.72rem">Episódio ' + Ep.num + ' · etapa ' + P.step + ' de 10</div><div class="h3">' + esc(Ep.title) + '</div></div><button class="iconbtn" data-act="plSheet" aria-label="Mapa">' + I('list', 20) + '</button></div><button data-act="plSheet" class="stack" style="--gap:8px;text-align:left;width:100%">' + C.segs(P.step, s.prog[Ep.num] || P.step) + '<span class="row base" style="--gap:8px"><span class="num" style="color:var(--orange)">' + pad2(P.step) + '</span><span class="h3">' + esc(cur.name) + '</span><span class="sm grow" style="white-space:nowrap;overflow:hidden;text-overflow:ellipsis">' + esc(cur.pt) + '</span><span class="xs" style="font-weight:800;color:var(--blue)">Mapa</span></span></button></div>'; }
  function stepList(Ep, s) { const max = s.prog[Ep.num] || 1; return D().STEPS.map((x) => { const now = x.n === P.step, reached = x.n <= max, done = reached && !now; return (x.group ? '<div class="lbl" style="padding:14px 4px 6px">' + x.group + '</div>' : '') + '<button class="steprow ' + (now ? 'now' : done ? 'done' : reached ? '' : 'locked') + '" ' + (reached ? 'data-act="plGo" data-arg="' + x.n + '"' : 'disabled') + '><span class="n">' + (done ? I('check', 14) : x.n) + '</span><span class="grow"><span class="h3" style="display:block;font-size:1rem">' + esc(x.name) + '</span><span class="sm">' + esc(x.pt) + '</span></span><span class="xs" style="font-weight:800;color:' + (now ? 'var(--orange)' : done ? 'var(--green)' : 'var(--muted)') + '">' + (now ? 'Você está aqui' : done ? 'Feito' : '+10') + '</span></button>'; }).join(''); }
  function foot(Ep, s) { const lock = gate(Ep, s, P.step), blocked = !!lock, nx = D().STEPS[P.step]; return '<div class="player-foot"><button class="btn prev" data-act="plPrev" aria-label="Anterior"' + (P.step > 1 ? '' : ' disabled') + '>' + I('back', 22) + '</button><button class="btn next"' + (blocked ? ' disabled' : ' data-act="plNext"') + '><span style="min-width:0"><span class="kicker">' + (blocked ? lock : P.step === 10 ? 'Última etapa · +40 pontos' : 'Próxima · ' + pad2(P.step + 1) + ' · +10') + '</span><span style="display:block;white-space:nowrap;overflow:hidden;text-overflow:ellipsis">' + esc(P.step === 10 ? 'Concluir episódio' : nx.name) + '</span></span>' + I('next', 22) + '</button></div>'; }

  const STEP = {};
  STEP[1] = (Ep) => '<div class="now-card stack" style="--gap:16px;min-height:340px;justify-content:space-between"><div class="bgimg" style="background-image:url(assets/img/gen/bg/home.webp);opacity:.3"></div><div class="row between"><span class="kick">Abertura</span><span class="pill" style="background:var(--navy2);color:#fff">Ep. ' + pad2(Ep.num) + '</span></div><div><div class="h1" style="color:#fff">' + esc(Ep.title) + '</div><p class="p mt8" style="color:var(--onNavy)">' + esc(Ep.synopsis) + '</p></div><div class="stack" style="--gap:10px"><button class="btn light" data-act="plPlay" style="align-self:flex-start">' + playIco() + '<span>' + (Ep.introAudio ? (P.playing ? 'Pausar a abertura' : 'Ouvir a abertura') : 'Ouvir a vinheta') + '</span></button>' + (Ep.introAudio ? '<div class="row" style="--gap:10px"><div class="bar grow"><i id="pl-bar" style="width:' + (P.aD ? Math.round(P.aT / P.aD * 100) : 0) + '%"></i></div><span class="xs" id="pl-time" style="color:#fff">' + fmt(P.aT) + ' / ' + (P.aD ? fmt(P.aD) : '—') + '</span></div>' : '') + '</div></div><p class="p-read">' + (Ep.introAudio ? 'A mesma música volta no fim do episódio para você cantar junto.' : 'A música do episódio abre, marca e fecha a aula. Você ouve a abertura agora e canta junto no fim.') + '</p>';
  // Música (etapas 2 e 10): título, tradução, player e instrução ficam fixos; só a letra rola.
  const song = (Ep) => { const len = Ep.lyrics.length; return { dock: '<div class="stack" style="--gap:8px"><div class="row between"><div><div class="lbl">' + (P.step === 2 ? 'Música · 1ª passada' : 'Música · cante junto') + '</div><div class="h2 mt4">' + esc(Ep.songTitle) + '</div></div><button class="row" data-act="plTrans" style="--gap:8px;font-weight:800;min-height:44px">Tradução <span class="toggle' + (P.trans ? ' on' : '') + '"><i></i></span></button></div>' + '<div class="card row" style="--gap:12px;padding:8px 14px 8px 8px"><button class="playbtn' + (P.playing ? '' : ' navy') + '" data-act="plPlay" aria-label="Tocar" style="width:48px;height:48px">' + playIco() + '</button><div class="bar grow"><i id="pl-bar" style="width:' + (Ep.songAudio && P.aD ? Math.round(P.aT / P.aD * 100) : Math.round((P.line + (P.playing ? 1 : 0)) / len * 100)) + '%"></i></div><span class="xs" id="pl-time">' + (Ep.songAudio ? fmt(P.aT) + ' / ' + (P.aD ? fmt(P.aD) : '—') : '0:' + pad2(8 + P.line * 7)) + '</span></div>' + (!Ep.songAudio ? '<p class="xs">Sem a gravação desta música no protótipo: a trilha é sintetizada e a letra avança sozinha.</p>' : '') + (P.step === 10 ? '<p class="sm">Agora é sua vez. Cante junto: a letra acompanha a música. +10 pontos ao terminar.</p>' : '') + '</div>', body: '<div class="stack" style="--gap:2px">' + Ep.lyrics.map((l, i) => '<div class="dialog-line' + (i === P.line ? ' on' : '') + '" id="ly' + i + '"><div class="en" style="font-size:' + (i === P.line ? '1.2rem' : '1.08rem') + ';color:' + (i === P.line ? 'var(--navy)' : 'var(--muted)') + '">' + esc(l.en) + '</div>' + (P.trans ? '<div class="pt sm" style="margin-top:2px">' + esc(l.pt) + '</div>' : '') + '</div>').join('') + '</div>' + (P.step === 2 && !need(Ep, TIE.store.s, 2) ? '<button class="card row" data-act="plNext" style="--gap:12px;border:2px dashed var(--navy)">' + I('download', 22) + '<span class="p"><b>Próximo: baixar o e-book ' + Ep.ebook + '.</b> O download libera o episódio.</span></button>' : '') }; };
  STEP[2] = song; STEP[10] = song;
  STEP[3] = (Ep, s) => '<div class="card stack" style="--gap:12px"><div class="row between"><span class="lbl">E-book ' + pad2(Ep.ebook) + ' · Episódios ' + Ep.ebookEps + '</span><span class="pill">PDF</span></div><div class="h1">' + esc(Ep.ebookTitle) + '</div><p class="p-read">' + esc(Ep.scope) + '</p><div class="sm">Diálogo bilíngue, Take Away, exercícios e gabarito</div></div>' + (s.ebooks[Ep.ebook] ? '<div class="card gr row" style="--gap:12px"><span class="iconbtn" style="background:var(--green);color:#fff;border:0">' + I('check', 20) + '</span><span class="p"><b style="color:var(--green)">E-book baixado.</b> O episódio está liberado.</span></div>' : C.btn(P.dl === 'busy' ? 'Baixando…' : 'Baixar e-book ' + Ep.ebook, { act: 'plDownload', icon: 'download', cls: 'block', kind: P.dl === 'busy' ? 'navy' : '' }));
  STEP[4] = (Ep) => { const scene = Ep.num === 2 ? 'assets/img/gen/scene/cafe-counter.webp' : 'assets/img/gen/bg/home.webp'; return '<div class="lbl">Cena · Act 1</div>' + (Ep.sceneVideo ? '<video src="' + Ep.sceneVideo + '" controls preload="metadata" style="width:100%;border-radius:18px;background:var(--navy)"></video>' : '<div class="scene"><div class="img" style="background-image:url(' + scene + ')"></div><div class="sub"><span class="ptl">' + esc(Ep.sceneNote) + '</span></div></div>') + '<div class="chips">' + Ep.cast.map((n) => '<span class="pill" style="min-height:36px"><b style="width:26px;height:26px;border-radius:50%;background:' + D().CAST[n][1] + ';color:#fff;display:inline-flex;align-items:center;justify-content:center;font-size:.7rem">' + D().CAST[n][0] + '</b>' + n + '</span>').join('') + '</div>' + '<div class="lbl mt8">Vocabulário visual · toque para ouvir</div><div class="grid2">' + Ep.visual.map((v) => '<button class="card" data-act="say" data-arg="' + esc(v.en) + '" style="padding:12px 14px"><div class="en">' + esc(v.en) + '</div><div class="sm">' + esc(v.pt) + '</div></button>').join('') + '</div><div class="xs">Ao seguir para a próxima etapa, estas palavras entram na sua Revisão.</div>'; };
  // Etapas 5 e 6 devolvem { dock, body }: o dock fica fixo sob o cabeçalho e só o body rola.
  STEP[5] = (Ep) => ({ dock: '<div class="row" style="--gap:10px"><button class="playbtn' + (P.playing ? '' : ' navy') + '" data-act="plPlay" aria-label="Tocar diálogo" style="width:48px;height:48px">' + playIco() + '</button><div class="grow"><div class="h3" style="font-size:.95rem">' + (P.playing ? 'Tocando' : 'Ouvir tudo') + '</div><div class="xs">' + (P.playing ? 'rolagem automática' : 'ou toque numa fala') + '</div></div><div class="seg">' + [0.75, 1, 1.25].map((v) => '<button class="' + (P.speed === v ? 'on' : '') + '" data-act="plSpeed" data-arg="' + v + '">' + String(v).replace('.', ',') + '×</button>').join('') + '</div></div>', body: '<div><div class="lbl">' + esc(Ep.dialogTitle) + '</div><p class="p mt4">' + esc(Ep.dialogSub) + '</p></div><div class="stack" style="--gap:4px">' + Ep.dialog.map((d, i) => '<button class="dialog-line' + (i === P.line ? ' on' : '') + (d.stage ? ' stage' : '') + '" data-act="plLine" data-arg="' + i + '" id="dl' + i + '">' + (d.who ? '<div class="who">' + esc(d.who.toUpperCase()) + '</div>' : '') + '<div class="' + (TIE.app.isDesktop() ? 'grid' : 'stack') + '" style="--gap:3px"><div class="en">' + esc(d.en) + '</div><div class="pt">' + esc(d.pt) + '</div></div>' + (d.err || d.hook ? '<div class="note' + (d.err ? ' err' : '') + '">' + esc(d.err || d.hook) + '</div>' : '') + '</button>').join('') + '</div>' });
  STEP[6] = (Ep, s) => { const m = Ep.mic[P.micIdx], sc = s.scores[Ep.num + '-' + P.micIdx], training = TIE.personalize.build(s.profile).defaults.training, fbObj = P.fb || (sc != null ? { score: sc, praise_pt: m.fb, issues: [] } : null);
    const status = P.mic === 'rec' ? 'Ouvindo… toque para parar' : P.mic === 'busy' ? 'Avaliando…' : fbObj ? 'Toque no microfone para tentar de novo' : 'Toque no microfone e fale · +5 a +15';
    const fb = fbObj && P.mic !== 'rec' && P.mic !== 'busy' ? '<div class="fb ' + (fbObj.score >= 8 ? 'ok' : 'fix') + ' row pop" style="--gap:12px;align-items:flex-start;padding:10px 12px">' + (training && !P.showScore ? '<button class="btn link" data-act="plShowScore" style="flex:none;min-height:0;padding:0">Ver nota</button>' : '<span class="num" style="font-size:1.6rem;line-height:1;flex:none">' + fbObj.score + '<span class="xs muted">/10</span></span>') + '<span class="sm" style="color:var(--navy)">' + esc(fbObj.praise_pt || m.fb) + (fbObj.heard ? '<br>Entendi: “' + esc(fbObj.heard) + '”' : '') + (fbObj.issues || []).map((x) => '<br><b>' + esc(x.word) + ':</b> ' + esc(x.tip_pt)).join('') + '</span></div>' : '';
    return { dock: '<div class="card stack" style="--gap:8px;padding:14px 16px"><div class="lbl">Frase ' + (P.micIdx + 1) + ' de ' + Ep.mic.length + ' · diga em voz alta</div><div class="row" style="--gap:12px"><div class="grow stack" style="--gap:4px"><div class="h2">' + esc(m.en) + '</div>' + (m.tip ? '<div class="sm"><b>Dica de boca:</b> ' + esc(m.tip) + '</div>' : '') + '</div><button class="mic' + (P.mic === 'rec' ? ' rec' : '') + '" data-act="plRecord" aria-label="Gravar" style="width:60px;height:60px">' + I(P.mic === 'rec' ? 'stop' : 'mic', 28) + '</button></div><div class="row" style="--gap:10px"><button class="btn light compact" data-act="say" data-arg="' + esc(m.en) + '">' + I('speaker', 18) + '<span>Ouvir</span></button><div class="waves mini ' + (P.mic === 'rec' ? 'rec' : P.mic === 'done' ? 'done' : '') + '">' + Array.from({ length: 10 }, (_, i) => '<i style="height:' + (8 + ((i * 7) % 16)) + 'px;animation-delay:' + (i * .06) + 's"></i>').join('') + '</div><span class="xs grow" style="font-weight:700;line-height:1.3">' + status + '</span></div>' + fb + '</div>',
      body: '<div class="stack" style="--gap:6px">' + Ep.mic.map((x, i) => { const v = s.scores[Ep.num + '-' + i]; return '<button class="card row" data-act="plMicPick" data-arg="' + i + '" style="--gap:10px;padding:12px 14px;' + (i === P.micIdx ? 'border-color:var(--navy);border-width:2px' : '') + '"><span class="num" style="color:var(--orange);width:20px">' + (i + 1) + '</span><span class="h3 grow" style="font-size:1rem">' + esc(x.en) + '</span><span class="num" style="font-size:1rem;color:' + (v == null ? 'var(--muted)' : v >= 8 ? 'var(--green)' : 'var(--blue)') + '">' + (v == null ? '—' : training && !P.showScore ? '✓' : v + '/10') + '</span></button>'; }).join('') + '</div><p class="sm">A nota mede quanto da sua fala foi entendida, não quanto você soa americano.</p>' }; };
  STEP[7] = (Ep) => { const pr = Ep.pron; return TIE.blocks(Ep.lesson, 'EVITE') + '<div class="card navy stack" style="--gap:12px"><div class="lbl" style="color:var(--onNavy)">' + esc(pr.k) + '</div>' + pr.parts.map((pp) => '<p class="p"><b>' + esc(pp.b) + '</b> ' + esc(pp.t) + '</p>').join('') + (pr.pairs && pr.pairs.length ? '<div class="stack" style="--gap:6px">' + pr.pairs.map((pa) => '<div class="grid2" style="padding:10px 12px;border-radius:12px;background:var(--navy2);gap:4px 10px"><b>' + esc(pa.a) + '</b><span>' + esc(pa.b) + '</span><span class="xs" style="grid-column:1/-1;color:var(--onNavy)">' + esc(pa.c) + '</span></div>').join('') + '</div>' : '') + '<div class="chips">' + pr.words.map((w) => '<button class="chip" data-act="say" data-arg="' + esc(w) + '" style="background:#fff;color:var(--navy);border-color:#fff">' + I('play', 12) + esc(w) + '</button>').join('') + '</div></div>'; };
  STEP[8] = (Ep) => '<p class="p-read">Lista fechada. Toque para ouvir: o que você já ouviu fica azul. Ao seguir, as expressões-chave entram na sua Revisão.</p><div class="card" style="padding:6px 16px"><div class="lbl or" style="padding:12px 0 6px">Expressões-chave</div>' + Ep.awayExp.map((a) => '<button class="listrow sayrow' + heard(a.en) + '" data-act="sayMark" data-arg="' + esc(a.en) + '"><span class="sayico">' + I('speaker', 16) + '</span><span class="grow stack" style="--gap:2px"><span class="row between top" style="--gap:10px"><span class="en">' + esc(a.en) + '</span><span class="pt" style="text-align:right">' + esc(a.pt) + '</span></span>' + (a.note ? '<span class="sm">' + esc(a.note) + '</span>' : '') + '</span></button>').join('') + '</div><div class="card stack" style="--gap:10px"><div class="lbl or">Palavras-chave</div><div class="chips">' + Ep.awayWords.map((w) => '<button class="pill saypill' + heard(w) + '" data-act="sayMark" data-arg="' + esc(w) + '">' + I('speaker', 14) + esc(w) + '</button>').join('') + '</div></div>';
  // Take Action: uma pergunta por vez. P.exIdx = exercício, P.itIdx = pergunta dentro dele; ao abrir, cai na primeira sem resposta.
  const heard = (t) => (TIE.ui.heard.has(t) ? ' heard' : '');
  const exKey = (Ep, x, j) => Ep.num + '-' + x + '-' + j;
  const dots = (n, cur, w) => '<div class="row" style="--gap:5px">' + Array.from({ length: n }, (_, i) => '<i style="height:7px;border-radius:4px;display:block;width:' + (i === cur ? w : 7) + 'px;background:' + (i === cur ? 'var(--orange)' : i < cur ? 'var(--blue)' : 'var(--line2)') + '"></i>').join('') + '</div>';
  STEP[9] = (Ep, s) => {
    if (P.itIdx == null) { const at = Ep.ex.flatMap((ex, x) => ex.items.map((_, j) => [x, j])).find(([x, j]) => s.exAns[exKey(Ep, x, j)] == null) || [0, 0]; P.exIdx = at[0]; P.itIdx = at[1]; }
    const ex = Ep.ex[P.exIdx], it = ex.items[P.itIdx], key = exKey(Ep, P.exIdx, P.itIdx), ans = s.exAns[key], answered = ans != null, ok = ans === it.a;
    const right = ex.items.filter((x, j) => s.exAns[exKey(Ep, P.exIdx, j)] === x.a).length, seen = ex.items.filter((_, j) => s.exAns[exKey(Ep, P.exIdx, j)] != null).length;
    const lastIt = P.itIdx === ex.items.length - 1, end = lastIt && P.exIdx === Ep.ex.length - 1, hasAudio = ex.audio === 'tts' || ex.audio === 'song';
    const card = '<div class="card stack pop" style="--gap:12px"><div class="row between"><span class="lbl">Pergunta ' + (P.itIdx + 1) + ' de ' + ex.items.length + (seen ? ' · ' + right + '/' + seen + ' certas' : '') + '</span>' + dots(ex.items.length, P.itIdx, 16) + '</div><div class="h2">' + esc(it.q) + '</div><div class="stack" style="--gap:8px">' + it.opts.map((o, i) => '<button class="opt' + (answered && i === it.a ? ' right' : answered && i === ans ? ' wrong' : '') + '" ' + (answered ? 'disabled' : 'data-act="plEx" data-arg="' + key + ':' + i + '"') + '><span class="key">' + 'ABCD'[i] + '</span><span>' + esc(o) + '</span></button>').join('') + '</div>' + (answered ? '<div class="fb ' + (ok ? 'ok' : 'err') + '">' + (ok ? 'Isso. +5 pontos.' : 'Quase. A resposta é “' + esc(it.opts[it.a]) + '”.') + (it.fix ? ' ' + esc(it.fix) : '') + '</div>' : '') + '</div>';
    const nav = '<div class="row between" style="--gap:10px">' + (P.exIdx || P.itIdx ? C.btn('Anterior', { kind: 'ghost compact', act: 'plExGo', arg: -1, icon: 'back' }) : '<span></span>') + (end ? '<span class="sm tc" style="font-weight:700">Última pergunta. Siga para ' + esc(D().STEPS[9].name) + ' abaixo.</span>' : C.btn(lastIt ? 'Próximo exercício' : 'Próxima pergunta', { kind: (answered ? '' : 'ghost') + ' compact', act: 'plExGo', arg: 1, iconR: 'next' })) + '</div>';
    return '<div class="row between"><div class="h3">Exercício ' + (P.exIdx + 1) + ' de ' + Ep.ex.length + ' · <span class="muted" style="font-weight:600">' + esc(ex.kind) + '</span></div>' + dots(Ep.ex.length, P.exIdx, 22) + '</div><div><div class="h2">' + esc(ex.title) + '</div>' + (ex.intro ? '<p class="p mt8">' + esc(ex.intro) + '</p>' : '') + '</div>' + (hasAudio ? C.btn(ex.audioLabel || 'Ouvir', { kind: 'navy compact', act: 'plExAudio', icon: 'speaker' }) : '') + card + nav;
  };

  TIE.screens.player = {
    title: 'Episódio',
    render(p) {
      const s = TIE.store.s, Ep = D().EPS[+p.ep]; if (!Ep) { setTimeout(() => TIE.router.replace('trilha'), 0); return { html: '' }; }
      const prog = s.prog[Ep.num] || 1, step = +p.step || (prog >= 10 ? 1 : prog);
      // Sem atalho: um link para uma etapa à frente cai na última etapa alcançada.
      if (step > prog) { setTimeout(() => TIE.router.replace('episodio/' + Ep.num + '/' + prog), 0); return { html: '' }; }
      if (!P || P.ep !== Ep.num || P.step !== step) { stopAll(); const keep = P && P.ep === Ep.num ? { trans: P.trans, speed: P.speed } : {}; P = Object.assign(fresh(Ep.num, step), keep); }
      const desk = TIE.app.isDesktop();
      const part = STEP[step](Ep, s), dock = part.dock ? '<div class="player-dock">' + part.dock + '</div>' : '';
      const main = head(Ep, s) + dock + '<div class="scroll" id="pl-scroll"><div class="wrap" style="--wrap:760px;padding-top:16px"><div class="stack enter" style="--gap:16px">' + (part.dock ? part.body : part) + '</div></div></div>' + foot(Ep, s);
      const html = desk ? '<div style="display:flex;flex:1;min-height:0"><aside style="width:300px;flex:none;background:#fff;border-right:1.5px solid var(--line);padding:18px 16px;overflow-y:auto"><button class="btn link" data-act="plClose" style="justify-content:flex-start">' + I('back', 18) + '<span>Voltar para Hoje</span></button><div class="lbl mt8">E-book ' + Ep.ebook + '</div><div class="h2 mt4">Episódio ' + pad2(Ep.num) + '</div><p class="sm mt8">' + esc(Ep.scope) + '</p><div class="mt12">' + stepList(Ep, s) + '</div></aside><div class="view">' + main + '</div></div>' : main;
      const sheet = P.sheet ? '<div class="overlay"><div class="scrim" data-act="plSheet"></div><div class="sheet"><div class="grab"></div><div class="row between top"><div><div class="lbl">Mapa do episódio ' + Ep.num + '</div><div class="h2 mt4">' + esc(Ep.title) + '</div></div><button class="iconbtn" data-act="plSheet" aria-label="Fechar">' + I('close', 18) + '</button></div><div class="mt8">' + stepList(Ep, s) + '</div></div></div>' : '';
      return { html, overlay: sheet, title: 'Ep. ' + Ep.num + ' · ' + D().STEPS[step - 1].name };
    },
    after() {
      if (!P) return;
      // Rolagem automática: a fala (etapa 5) ou o verso (etapas 2 e 10) que está tocando fica no meio da tela.
      if (P.playing && [2, 5, 10].includes(P.step)) { const el = document.getElementById((P.step === 5 ? 'dl' : 'ly') + P.line); if (el) el.scrollIntoView({ block: 'center', behavior: 'smooth' }); }
      if (P.step === 4) { const v = document.querySelector('#pl-scroll video'); if (v) v.onended = () => { mark(4); re(); }; }
    },
    leave() { stopAll(); P = null; }
  };
  TIE.act.plClose = () => { stopAll(); TIE.router.go('inicio'); };
  TIE.act.plSheet = () => { P.sheet = !P.sheet; re(); };
  TIE.act.plGo = (n) => { P.sheet = false; setStep(+n); };
  function setStep(n, award) { const s = TIE.store.s, ep = P.ep; if (award && n > (s.prog[ep] || 1)) TIE.game.award('step'); s.prog[ep] = Math.max(s.prog[ep] || 1, n); TIE.store.save(); TIE.router.go('episodio/' + ep + '/' + n); }
  TIE.act.plPrev = () => { if (P.step > 1) setStep(P.step - 1); };
  TIE.act.plNext = () => { const s = TIE.store.s; if (gate(E(), s, P.step)) return; if (P.step === 10) { stopAll(); s.prog[P.ep] = 10; s.epsDone[P.ep] = true; TIE.store.save(); TIE.game.award('episode'); TIE.app.confetti(); TIE.router.go('concluido/' + P.ep); return; } setStep(P.step + 1, true); };
  TIE.act.plTrans = () => { P.trans = !P.trans; re(); };
  TIE.act.plSpeed = (v) => { P.speed = +v; re(); };
  TIE.act.plDownload = () => { if (P.dl !== 'idle') return; P.dl = 'busy'; re(); setTimeout(() => { TIE.store.s.ebooks[E().ebook] = true; P.dl = 'idle'; TIE.store.save(); TIE.sound.sfx.ok(); re(); }, 1300); };
  TIE.act.plShowScore = () => { P.showScore = true; re(); };
  TIE.act.plPlay = () => {
    const ep = E(), src = stepAudio(ep, P.step);
    if (P.playing) { stopAll(); return re(); }
    if (src) { const a = audio = new Audio(src); a.addEventListener('timeupdate', () => { if (!P || audio !== a) return; P.aT = a.currentTime; P.aD = a.duration || 0; const bar = document.getElementById('pl-bar'), t = document.getElementById('pl-time'); if (bar && P.aD) bar.style.width = Math.round(P.aT / P.aD * 100) + '%'; if (t) t.textContent = fmt(P.aT) + ' / ' + (P.aD ? fmt(P.aD) : '—'); if (P.step === 2 || P.step === 10) { const n = Math.min(ep.lyrics.length - 1, Math.floor(P.aT / (P.aD || 1) * ep.lyrics.length)); if (n !== P.line) { P.line = n; re(); } } }); a.addEventListener('ended', () => { if (P && audio === a) { P.playing = false; mark(P.step); if (P.step === 10) TIE.game.award('song'); re(); } }); if (P.aD && P.aT > 0 && P.aT < P.aD - .5) a.currentTime = P.aT; else { P.aT = 0; P.line = 0; } audio.play().catch(() => TIE.app.toast('O navegador bloqueou o áudio. Toque de novo.')); P.playing = true; return re(); }
    if (P.step === 2 || P.step === 10) { P.playing = true; if (P.line >= ep.lyrics.length - 1) P.line = 0; TIE.sound.synth.play({ bpm: 104, key: ep.num * 2 }); P.timer = setInterval(() => { if (!P) return; if (P.line >= ep.lyrics.length - 1) { stopAll(); mark(P.step); if (P.step === 10) TIE.game.award('song'); } else P.line++; re(); }, 2600); return re(); }
    if (P.step === 1) { const tk = P.tk = Date.now(); P.playing = true; TIE.sound.synth.play({ bpm: 112, key: 3 }); setTimeout(() => { if (P && P.step === 1 && P.playing && P.tk === tk) { stopAll(); mark(1); re(); } }, 15000); return re(); }
    if (P.step === 5) { P.playing = true; re(); speakFrom(P.line); }
  };
  function speakFrom(i) { const ep = E(); if (!P || !P.playing || i >= ep.dialog.length) { if (P) { if (P.playing && i >= ep.dialog.length) mark(5); P.playing = false; re(); } return; } P.line = i; re(); const d = ep.dialog[i]; if (d.stage) { setTimeout(() => speakFrom(i + 1), 900); return; } TIE.speech.say(d.en, { who: d.who, rate: P.speed }).then(() => { if (P && P.playing && P.line === i) setTimeout(() => speakFrom(i + 1), 250); }); }
  TIE.act.plLine = (i) => { const d = E().dialog[+i]; P.line = +i; if (P.playing) { TIE.speech.stop(); speakFrom(+i); return; } re(); if (!d.stage) TIE.speech.say(d.en, { who: d.who, rate: P.speed }); };
  TIE.act.plMicPick = (i) => { P.micIdx = +i; P.mic = 'idle'; P.fb = null; re(); };
  TIE.act.plRecord = async () => {
    const ep = E(), m = ep.mic[P.micIdx], key = ep.num + '-' + P.micIdx;
    if (P.mic === 'rec') { P.stopper && P.stopper(); return; } if (P.mic === 'busy') return;
    let rec = null, heard = '', lis = null;
    if (TIE.speech.canRecord) { try { rec = await TIE.speech.record({ maxMs: 7000 }); } catch (e) { rec = null; } }
    TIE.sound.sfx.rec(); P.mic = 'rec'; P.fb = null; re();
    if (rec && TIE.speech.canListen) lis = TIE.speech.listen({ onInterim: (t) => { heard = t; }, onFinal: (t) => { heard = t; } });
    P.stopper = async () => { P.stopper = null; if (!P) return; lis && lis.stop(); P.mic = 'busy'; re(); let r; if (rec) { const out = await rec.stop(); r = await TIE.ai.pronounce(out.b64, m.en, heard); } else r = { score: m.result, praise_pt: m.fb, issues: [], source: 'roteiro' }; if (!P) return; TIE.store.s.scores[key] = r.score; TIE.store.save(); P.fb = r; P.mic = 'done'; TIE.game.award(r.score >= 8 ? 'mic_good' : 'mic_try'); re(); };
    setTimeout(() => P && P.mic === 'rec' && P.stopper && P.stopper(), rec ? 5500 : 2000);
  };
  TIE.act.plEx = (arg) => { const key = arg.slice(0, arg.lastIndexOf(':')), i = +arg.slice(arg.lastIndexOf(':') + 1); TIE.store.s.exAns[key] = i; TIE.store.save(); const [ep, ex, j] = key.split('-').map(Number); if (D().EPS[ep].ex[ex].items[j].a === i) TIE.game.award('ex_right'); else TIE.sound.sfx.soft(); re(); };
  // Anda uma pergunta para a frente (+1) ou para trás (-1), passando de um exercício para o outro.
  TIE.act.plExGo = (d) => { const ex = E().ex; if (+d > 0) { if (P.itIdx < ex[P.exIdx].items.length - 1) P.itIdx++; else if (P.exIdx < ex.length - 1) { P.exIdx++; P.itIdx = 0; } } else if (P.itIdx > 0) P.itIdx--; else if (P.exIdx > 0) { P.exIdx--; P.itIdx = ex[P.exIdx].items.length - 1; } TIE.speech.stop(); re(); const sc = document.getElementById('pl-scroll'); if (sc) sc.scrollTop = 0; };
  TIE.act.plExAudio = () => { const ep = E(), ex = ep.ex[P.exIdx]; if (ex.audio === 'song' && ep.songAudio) { if (audio) { audio.pause(); audio = null; } audio = new Audio(ep.songAudio); audio.play().catch(() => {}); return; } const it = ex.items[P.itIdx || 0]; TIE.speech.say(it.say || it.q.replace(/[“”]/g, ''), { rate: .9 }); };
})();
