// Downloads the exact woff2 files Google Fonts serves to a modern Chrome for the prototype's
// stylesheet (Archivo italic 900 + Figtree 400..800), keeps only the latin and latin-ext subsets,
// and writes css/fonts.css with the same @font-face blocks pointing at ../fonts/*.woff2.
// Run once: npx tsx packages/ui/scripts/fetchFonts.ts
import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const CSS_URL =
  'https://fonts.googleapis.com/css2?family=Archivo:ital,wght@1,900&family=Figtree:wght@400..800&display=swap';
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/141.0.0.0 Safari/537.36';
const SUBSETS = new Set(['latin', 'latin-ext']);

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

async function main(): Promise<void> {
  const css = await (await fetch(CSS_URL, { headers: { 'User-Agent': UA } })).text();
  // Google emits "/* subset */\n@font-face {...}" pairs.
  const blocks = [...css.matchAll(/\/\*\s*([\w-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/g)];
  if (!blocks.length) throw new Error(`unexpected CSS from Google Fonts:\n${css}`);
  await mkdir(join(root, 'fonts'), { recursive: true });
  const out: string[] = [
    '/* Self-hosted copies of the Google Fonts the prototype loads (Archivo italic 900, Figtree 400..800).',
    '   Generated by scripts/fetchFonts.ts; same @font-face blocks and unicode ranges, latin + latin-ext only. */',
  ];
  for (const [, subset, block] of blocks) {
    if (!subset || !block || !SUBSETS.has(subset)) continue;
    const family = /font-family:\s*'([^']+)'/.exec(block)?.[1];
    const url = /url\((https:\/\/fonts\.gstatic\.com\/[^)]+\.woff2)\)/.exec(block)?.[1];
    if (!family || !url) throw new Error(`cannot parse block:\n${block}`);
    const name = `${family.toLowerCase()}-${subset}.woff2`;
    const bytes = new Uint8Array(await (await fetch(url, { headers: { 'User-Agent': UA } })).arrayBuffer());
    await writeFile(join(root, 'fonts', name), bytes);
    out.push(`/* ${subset} */`, block.replace(url, `../fonts/${name}`));
    console.log(`${name}  ${bytes.byteLength} bytes  <- ${url}`);
  }
  await writeFile(join(root, 'css', 'fonts.css'), `${out.join('\n')}\n`);
}

await main();
