// Generates src/icons.tsx from prototipo/js/ui/icons.js: the path table P becomes one JSX fragment
// per icon (the prototype's inner SVG markup is already valid JSX), and Icon renders the same
// <svg> wrapper as TIE.icon(). Run: npx tsx packages/ui/scripts/genIconsTsx.ts
import { execFileSync } from 'node:child_process';
import { readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const repo = join(root, '..', '..');
const src = await readFile(join(repo, 'prototipo', 'js', 'ui', 'icons.js'), 'utf8');

const start = src.indexOf('const P = {');
const end = src.indexOf('};', start);
if (start < 0 || end < 0) throw new Error('icons.js: path table P not found');
// The table is a plain object literal of single-quoted strings; evaluate it as data.
const table = new Function(`return ${src.slice(start + 'const P = '.length, end + 1)}`)() as Record<string, string>;

const names = Object.keys(table);
const entries = names.map((n) => {
  const markup = table[n] ?? '';
  if (/[{}]/.test(markup)) throw new Error(`icon ${n}: markup is not plain SVG`);
  return `  ${JSON.stringify(n)}: () => <>${markup}</>,`;
});

const out = `// GENERATED by scripts/genIconsTsx.ts from prototipo/js/ui/icons.js. Do not edit by hand.
// Stroke icons (24×24), same markup as TIE.icon(name, size, extra).
import type { JSX } from 'preact';

export const ICON_NAMES = ${JSON.stringify(names)} as const;
export type IconName = (typeof ICON_NAMES)[number];

const P: Record<IconName, () => JSX.Element> = {
${entries.join('\n')}
};

export const isIconName = (name: string): name is IconName => Object.hasOwn(P, name);

export type IconProps = {
  /** Unknown names render an empty <svg>, like the prototype. */
  name: IconName | (string & {});
  /** Width and height in px (default 22). */
  size?: number;
  /** Extra attributes, the JSX form of TIE.icon's third argument (e.g. style). */
  extra?: JSX.SVGAttributes<SVGSVGElement>;
};

export function Icon({ name, size = 22, extra }: IconProps): JSX.Element {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      stroke-width="2.2"
      stroke-linecap="round"
      stroke-linejoin="round"
      aria-hidden="true"
      {...extra}
    >
      {isIconName(name) ? P[name]() : null}
    </svg>
  );
}
`;

const file = join(root, 'src', 'icons.tsx');
await writeFile(file, out);
execFileSync(
  process.execPath,
  [join(repo, 'node_modules', '@biomejs', 'biome', 'bin', 'biome'), 'format', '--write', file],
  {
    stdio: 'inherit',
  },
);
console.log(`icons.tsx: ${names.length} icons`);
