// GENERATED by scripts/genIconsTsx.ts from prototipo/js/ui/icons.js. Do not edit by hand.
// Stroke icons (24×24), same markup as TIE.icon(name, size, extra).
import type { JSX } from 'preact';

export const ICON_NAMES = [
  'home',
  'trail',
  'tv',
  'review',
  'profile',
  'play',
  'pause',
  'stop',
  'mic',
  'back',
  'next',
  'close',
  'check',
  'down',
  'plus',
  'speaker',
  'list',
  'lock',
  'flag',
  'chat',
  'wave',
  'music',
  'plane',
  'brief',
  'ear',
  'book',
  'cards',
  'pen',
  'clock',
  'bell',
  'heart',
  'game',
  'eye',
  'eyeoff',
  'repeat',
  'cc',
  'send',
  'bulb',
  'trophy',
  'download',
  'phone',
  'desktop',
  'power',
  'logout',
  'star',
  'fire',
  'coin',
  'target',
  'sparkle',
  'google',
  'apple',
] as const;
export type IconName = (typeof ICON_NAMES)[number];

const P: Record<IconName, () => JSX.Element> = {
  home: () => (
    <>
      <path d="M3.5 10.5 12 3.5l8.5 7" />
      <path d="M5.5 9.5V20h13V9.5" />
    </>
  ),
  trail: () => (
    <>
      <path d="M5 20c0-4 3-5 7-5s7-1 7-5-3-5-7-5-7 1-7 5" />
      <circle cx="5" cy="20" r="1.6" fill="currentColor" />
      <circle cx="19" cy="5" r="1.6" fill="currentColor" />
    </>
  ),
  tv: () => (
    <>
      <rect x="3" y="6" width="18" height="13" rx="3" />
      <path d="m8.5 2.5 3.5 3.5 3.5-3.5" />
    </>
  ),
  review: () => (
    <>
      <path d="M11 6 4 12l7 6V6Z" />
      <path d="M20 6l-7 6 7 6V6Z" />
    </>
  ),
  profile: () => (
    <>
      <circle cx="12" cy="8" r="4" />
      <path d="M4 21c0-4.4 3.6-7 8-7s8 2.6 8 7" />
    </>
  ),
  play: () => (
    <>
      <path d="M7 4.5v15l12.5-7.5z" fill="currentColor" stroke="none" />
    </>
  ),
  pause: () => (
    <>
      <rect x="6" y="5" width="4" height="14" rx="1" fill="currentColor" stroke="none" />
      <rect x="14" y="5" width="4" height="14" rx="1" fill="currentColor" stroke="none" />
    </>
  ),
  stop: () => (
    <>
      <rect x="6" y="6" width="12" height="12" rx="2" fill="currentColor" stroke="none" />
    </>
  ),
  mic: () => (
    <>
      <rect x="9" y="3" width="6" height="11" rx="3" />
      <path d="M5 11.5a7 7 0 0 0 14 0M12 18.5V21" />
    </>
  ),
  back: () => (
    <>
      <path d="M15 5 8 12l7 7" />
    </>
  ),
  next: () => (
    <>
      <path d="m9 5 7 7-7 7" />
    </>
  ),
  close: () => (
    <>
      <path d="M6 6l12 12M18 6 6 18" />
    </>
  ),
  check: () => (
    <>
      <path d="m5 12.5 4.5 4.5L19 7.5" />
    </>
  ),
  down: () => (
    <>
      <path d="m6 9 6 6 6-6" />
    </>
  ),
  plus: () => (
    <>
      <path d="M12 5v14M5 12h14" />
    </>
  ),
  speaker: () => (
    <>
      <path d="M4 9.5v5h3.5L12 18.5v-13L7.5 9.5z" />
      <path d="M15.5 9a4 4 0 0 1 0 6M18 6.5a7.5 7.5 0 0 1 0 11" />
    </>
  ),
  list: () => (
    <>
      <path d="M9 6h11M9 12h11M9 18h11" />
      <circle cx="4.5" cy="6" r="1.3" fill="currentColor" />
      <circle cx="4.5" cy="12" r="1.3" fill="currentColor" />
      <circle cx="4.5" cy="18" r="1.3" fill="currentColor" />
    </>
  ),
  lock: () => (
    <>
      <rect x="5" y="11" width="14" height="10" rx="2.5" />
      <path d="M8 11V8a4 4 0 0 1 8 0v3" />
    </>
  ),
  flag: () => (
    <>
      <path d="M5 21V4M5 4h11l-2 4 2 4H5" />
    </>
  ),
  chat: () => (
    <>
      <path d="M4 5.5h16v11H9l-5 4z" />
    </>
  ),
  wave: () => (
    <>
      <path d="M3 12h2M7 8v8M11 5v14M15 9v6M19 7v10" />
    </>
  ),
  music: () => (
    <>
      <path d="M9 18V5l11-2v13" />
      <circle cx="6.5" cy="18" r="2.5" />
      <circle cx="17.5" cy="16" r="2.5" />
    </>
  ),
  plane: () => (
    <>
      <path d="M10.5 13.5 3 11l1.5-1.5 8 1 4-4.5a2 2 0 0 1 3 3L15 13l1 8-1.5 1.5-2.5-7.5-3.5 3.5V21L7 22.5 5.5 18.5 1.5 17 3 15.5h2.5z" />
    </>
  ),
  brief: () => (
    <>
      <rect x="3" y="7" width="18" height="13" rx="2.5" />
      <path d="M9 7V5a2 2 0 0 1 2-2h2a2 2 0 0 1 2 2v2M3 13h18" />
    </>
  ),
  ear: () => (
    <>
      <path d="M7 9a5 5 0 0 1 10 0c0 3-3 4-3 7a3 3 0 0 1-5.5 1.5" />
      <path d="M10 9.5a2 2 0 0 1 4 0c0 1.5-2 2-2 3.5" />
    </>
  ),
  book: () => (
    <>
      <path d="M4 4.5h6a3 3 0 0 1 3 3V21a2.5 2.5 0 0 0-2.5-2.5H4z" />
      <path d="M20 4.5h-6a3 3 0 0 0-3 3V21a2.5 2.5 0 0 1 2.5-2.5H20z" />
    </>
  ),
  cards: () => (
    <>
      <rect x="3" y="7" width="13" height="13" rx="2.5" />
      <path d="M8 3.5h10a2.5 2.5 0 0 1 2.5 2.5v10" />
    </>
  ),
  pen: () => (
    <>
      <path d="M4 20h4L19 9a2.8 2.8 0 0 0-4-4L4 16z" />
      <path d="m13.5 6.5 4 4" />
    </>
  ),
  clock: () => (
    <>
      <circle cx="12" cy="12" r="8.5" />
      <path d="M12 7.5V12l3 2" />
    </>
  ),
  bell: () => (
    <>
      <path d="M6 16V11a6 6 0 0 1 12 0v5l1.5 2h-15z" />
      <path d="M10 21h4" />
    </>
  ),
  heart: () => (
    <>
      <path d="M12 20s-7.5-4.6-7.5-10A4.3 4.3 0 0 1 12 7.3 4.3 4.3 0 0 1 19.5 10c0 5.4-7.5 10-7.5 10z" />
    </>
  ),
  game: () => (
    <>
      <rect x="2.5" y="7" width="19" height="11" rx="5" />
      <path d="M7 10.5v4M5 12.5h4" />
      <circle cx="15.5" cy="11.5" r="1" fill="currentColor" />
      <circle cx="18" cy="13.5" r="1" fill="currentColor" />
    </>
  ),
  eye: () => (
    <>
      <path d="M2.5 12S6 5.5 12 5.5 21.5 12 21.5 12 18 18.5 12 18.5 2.5 12 2.5 12z" />
      <circle cx="12" cy="12" r="3" />
    </>
  ),
  eyeoff: () => (
    <>
      <path d="M3 3l18 18M10.6 5.6A9.7 9.7 0 0 1 12 5.5c6 0 9.5 6.5 9.5 6.5a17 17 0 0 1-3.2 4M6.2 6.9A17 17 0 0 0 2.5 12S6 18.5 12 18.5a9.4 9.4 0 0 0 4-.9" />
      <path d="M9.9 9.9a3 3 0 0 0 4.2 4.2" />
    </>
  ),
  repeat: () => (
    <>
      <path d="M17 2.5 20.5 6 17 9.5" />
      <path d="M3.5 11.5V10a4 4 0 0 1 4-4h13" />
      <path d="M7 21.5 3.5 18 7 14.5" />
      <path d="M20.5 12.5V14a4 4 0 0 1-4 4h-13" />
    </>
  ),
  cc: () => (
    <>
      <rect x="3" y="5" width="18" height="14" rx="3" />
      <path d="M10.5 10.2a2.2 2.2 0 1 0 0 3.6M17 10.2a2.2 2.2 0 1 0 0 3.6" />
    </>
  ),
  send: () => (
    <>
      <path d="M4 12 20 4l-4 16-4.5-6.5z" />
      <path d="M11.5 13.5 20 4" />
    </>
  ),
  bulb: () => (
    <>
      <path d="M9 18h6M10 21h4" />
      <path d="M12 3a6 6 0 0 0-3.5 10.9c.7.5 1 1.3 1 2.1h5c0-.8.3-1.6 1-2.1A6 6 0 0 0 12 3z" />
    </>
  ),
  trophy: () => (
    <>
      <path d="M7 4h10v5a5 5 0 0 1-10 0z" />
      <path d="M7 6H4a3 3 0 0 0 3 4M17 6h3a3 3 0 0 1-3 4M12 14v4M8 21h8" />
    </>
  ),
  download: () => (
    <>
      <path d="M12 3v12m0 0-4.5-4.5M12 15l4.5-4.5M4 20h16" />
    </>
  ),
  phone: () => (
    <>
      <rect x="7" y="2.5" width="10" height="19" rx="2.5" />
      <path d="M11 18.5h2" />
    </>
  ),
  desktop: () => (
    <>
      <rect x="2.5" y="4" width="19" height="13" rx="2" />
      <path d="M8.5 21h7M12 17v4" />
    </>
  ),
  power: () => (
    <>
      <path d="M12 3v8" />
      <path d="M6.4 6.6a8 8 0 1 0 11.2 0" />
    </>
  ),
  logout: () => (
    <>
      <path d="M15 4h3a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2h-3M10 17l-5-5 5-5M5 12h11" />
    </>
  ),
  star: () => (
    <>
      <path d="m12 3.5 2.6 5.5 6 .8-4.4 4.1 1.1 5.9L12 17l-5.3 2.8 1.1-5.9L3.4 9.8l6-.8z" />
    </>
  ),
  fire: () => (
    <>
      <path d="M12 21c-4 0-6.5-2.6-6.5-6 0-3 2-5 3-7 .5 2 1.5 2.8 2.5 3 0-3 1-6 4-8 0 3 1.5 4.5 2.5 6.5 1 1.8 1 3.2 1 4.5C18.5 18.4 16 21 12 21z" />
    </>
  ),
  coin: () => (
    <>
      <circle cx="12" cy="12" r="8.5" />
      <path d="M12 7.5v9M9.5 10a2.5 2 0 0 1 5 0c0 2-5 2-5 4a2.5 2 0 0 0 5 0" />
    </>
  ),
  target: () => (
    <>
      <circle cx="12" cy="12" r="8.5" />
      <circle cx="12" cy="12" r="4.5" />
      <circle cx="12" cy="12" r="1" fill="currentColor" />
    </>
  ),
  sparkle: () => (
    <>
      <path d="M12 3v4M12 17v4M3 12h4M17 12h4M6.3 6.3l2.5 2.5M15.2 15.2l2.5 2.5M6.3 17.7l2.5-2.5M15.2 8.8l2.5-2.5" />
    </>
  ),
  google: () => (
    <>
      <path
        d="M20.5 12.2c0-.6-.1-1.2-.2-1.7H12v3.3h4.8a4.1 4.1 0 0 1-1.8 2.7v2.2h2.9c1.7-1.6 2.6-3.9 2.6-6.5z"
        fill="#2A6FF5"
        stroke="none"
      />
      <path
        d="M12 21c2.4 0 4.4-.8 5.9-2.2L15 16.5c-.8.5-1.8.9-3 .9-2.3 0-4.3-1.6-5-3.7H4v2.3A9 9 0 0 0 12 21z"
        fill="#1F7A4C"
        stroke="none"
      />
      <path d="M7 13.7a5.4 5.4 0 0 1 0-3.4V8H4a9 9 0 0 0 0 8z" fill="#FFB627" stroke="none" />
      <path
        d="M12 6.6c1.3 0 2.5.5 3.4 1.3L18 5.4A9 9 0 0 0 4 8l3 2.3c.7-2.1 2.7-3.7 5-3.7z"
        fill="#F45A28"
        stroke="none"
      />
    </>
  ),
  apple: () => (
    <>
      <path
        d="M16.4 12.7c0-2.3 1.9-3.4 2-3.5a4.3 4.3 0 0 0-3.4-1.8c-1.4-.1-2.8.9-3.5.9-.7 0-1.8-.8-3-.8a4.5 4.5 0 0 0-3.8 2.3c-1.6 2.8-.4 7 1.2 9.3.8 1.1 1.7 2.4 2.9 2.3 1.2 0 1.6-.7 3-.7s1.8.7 3 .7c1.3 0 2.1-1.1 2.8-2.3a10 10 0 0 0 1.3-2.6 4 4 0 0 1-2.5-3.8zM14.1 5.9A4 4 0 0 0 15 3a4.1 4.1 0 0 0-2.7 1.4 3.8 3.8 0 0 0-1 2.8 3.4 3.4 0 0 0 2.8-1.3z"
        fill="currentColor"
        stroke="none"
      />
    </>
  ),
};

export const isIconName = (name: string): name is IconName => Object.hasOwn(P, name);

export type IconProps = {
  /** Unknown names render an empty <svg>, like the prototype. */
  name: IconName | (string & {});
  /** Width and height in px (default 22). */
  size?: number;
  /** Extra attributes, the JSX form of TIE.icon's third argument (e.g. style). */
  extra?: JSX.SVGAttributes<SVGSVGElement>;
};

export function Icon({ name, size = 22, extra }: IconProps): JSX.Element {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      stroke-width="2.2"
      stroke-linecap="round"
      stroke-linejoin="round"
      aria-hidden="true"
      {...extra}
    >
      {isIconName(name) ? P[name]() : null}
    </svg>
  );
}
