// Runs INSIDE the prototype page (page.evaluate): builds the parity fixture with the prototype's own
// functions (review.sync for the deck, ai.tutor/ai.report in demo mode for the Mic sessions), so every
// nested shape is exactly what the prototype itself would have saved under localStorage['tie.v6'].
// Self-contained on purpose: nothing from module scope is available in the page.
import type { Any } from '@tie/seed/loadPrototype';

export async function buildFixtureInPage(): Promise<Any> {
  const T = (window as Any).TIE;
  const D = T.data;
  T.store.reset();
  const s = T.store.s;
  const DAY = 864e5;
  const now = Date.now();
  const today = T.u.today();
  const dayIso = (ago: number) => new Date(now - ago * DAY).toISOString().slice(0, 10);
  const at = (ago: number, hhmm: string) => Date.parse(`${dayIso(ago)}T${hhmm}:00-03:00`);

  // Account + onboarding (the Ana demo profile, filled in completely)
  s.user = { name: 'Ana', fullName: 'Ana Beatriz Souza', email: 'ana@parity.test' };
  s.profile = {
    name: 'Ana',
    fullName: 'Ana Beatriz Souza',
    birth: '1994-05-12',
    age: '25-34',
    occup: 'trabalho',
    area: 'criativo',
    level: 'basico',
    goals: ['viagem', 'series', 'carreira'],
    deadline: '6m',
    history: ['escola', 'app'],
    fails: ['falar', 'tempo'],
    formats: ['series', 'animes', 'musica'],
    genres: ['comedia', 'suspense', 'shonen', 'musical', 'pop', 'anos80'],
    themes: ['comida', 'viagem', 'tecnologia'],
    diffs: ['pron', 'listening', 'shy'],
    mainDiff: 'pron',
    styles: ['vendo', 'falando'],
    company: 'desafio',
    feedback: 'direto',
    days: [1, 2, 3, 4, 5],
    minutes: 20,
    reminders: ['07:30', '20:00'],
    motives: ['viagem', 'carreira'],
    why: 'Quero viajar para Boston no ano que vem sem travar.',
    voice: null,
    assistant: 'margaret',
    avatar: 2,
  };
  s.onbStep = 7;
  Object.assign(s.draft, {
    fullName: s.profile.fullName,
    name: s.profile.name,
    birth: s.profile.birth,
    email: s.user.email,
    pass: '',
    goals: s.profile.goals.slice(),
    formats: s.profile.formats.slice(),
    genres: s.profile.genres.slice(),
    themes: s.profile.themes.slice(),
    diffs: s.profile.diffs.slice(),
    mainDiff: s.profile.mainDiff,
    styles: s.profile.styles.slice(),
    reminders: s.profile.reminders.slice(),
  });
  const P = T.personalize.build(s.profile);
  Object.assign(s.settings, {
    ts: 1,
    sound: true,
    hd: false,
    trans: true,
    slow: P.defaults.speed < 1,
    remind: true,
    phone: false,
    fx: true,
    free: false,
  });

  // Episode 1 at step 6 (Take the Mic): steps 1-5 behind, e-book 1 downloaded, half of the phrases
  // recorded, and a few Take Action answers already given.
  const E1 = D.EPS[1];
  s.prog = { 1: 6 };
  s.stepOk = { '1-1': true, '1-2': true, '1-4': true, '1-5': true };
  s.ebooks = { 1: true };
  s.scores = {};
  [8, 6, 9].forEach((v, i) => {
    if (i < E1.mic.length) s.scores[`1-${i}`] = v;
  });
  s.exAns = {};
  const ex0 = E1.ex[0];
  ex0.items.slice(0, 3).forEach((it: Any, j: number) => {
    s.exAns[`1-0-${j}`] = j === 1 ? (it.a + 1) % it.opts.length : it.a;
  });

  // Extras
  s.extras = { seen: { 'woods-and-beans': true }, dubs: { 'woods-and-beans': 7 }, best: 85, lastId: 'woods-and-beans' };

  // Mic: two finished sessions, generated by the demo tutor and the demo report
  const AS = T.assist.get('margaret');
  async function session(mode: string, mission: string, texts: string[], startedAt: number, secs: number) {
    const sess: Any = {
      mode,
      mission,
      extraId: 'woods-and-beans',
      ctx: P.ctx,
      turns: [],
      turn: 0,
      name: s.profile.name,
      ctxFormats: s.profile.formats,
      persona: AS.persona,
      aName: AS.name,
      aThe: T.assist.the(AS),
    };
    const o = T.ai.opener(sess);
    sess.turns.push({
      who: 'her',
      en: o.reply_en,
      pt: o.reply_pt,
      words: (o.words || []).map(([en, pt]: [string, string]) => ({ en, pt })),
    });
    for (const text of texts) {
      const me: Any = { who: 'me', en: text };
      sess.turns.push(me);
      const r = await T.ai.tutor(sess, text);
      me.fb = r.feedback;
      me.pron = r.pron_watch || [];
      sess.turn++;
      sess.turns.push({ who: 'her', en: r.reply_en, pt: r.reply_pt, words: r.new_words || [] });
    }
    const turns = sess.turns.map((t: Any) => ({
      who: t.who,
      en: t.en,
      pt: t.pt || '',
      fb: t.fb || null,
      pron: t.pron || [],
      words: t.words || [],
    }));
    const report = await T.ai.report({ ctx: P.ctx, mode, mission, turns, aName: AS.name, aThe: T.assist.the(AS) });
    return {
      id: T.u.uid(),
      at: startedAt,
      assistant: AS.k,
      mode,
      mission,
      extraId: 'woods-and-beans',
      secs,
      turns,
      report,
    };
  }
  const older = await session(
    'livre',
    P.missions[0].k,
    [
      'Hi Maggie! I am designer, I work with apps.',
      'I like very much anime and music.',
      'Yesterday I watch two episodes of Woods and Beans.',
      'My sister have a cat, she is so funny.',
    ],
    at(2, '20:00'),
    240,
  );
  const newer = await session(
    'missao',
    'viagem',
    [
      'Hello, I have a flight to Boston today.',
      'Yes, here is my passport.',
      'I have one bag, it depends of the weight?',
      'A window seat, please. Is it far?',
      'Thank you so much! Have a nice day.',
    ],
    at(1, '19:30'),
    300,
  );
  s.maggie = { secLeft: 3600 - older.secs - newer.secs, sessions: [newer, older] };

  // Review deck: what the finished steps unlock (Take a Look words), plus words saved from the
  // Extra and from the Mic, 12 cards in all; some reviewed and scheduled ahead, the rest due.
  T.review.sync();
  const x = D.EXTRAS.find((e: Any) => e.id === 'woods-and-beans');
  for (const [en, pt] of (x.vocab || []).slice(0, 2)) T.review.add(en, pt, `Extra · ${x.title}`);
  const micWords = [...newer.turns, ...older.turns].flatMap((t: Any) => t.words || []);
  for (const w of micWords) {
    if (s.deck.length >= 12) break;
    T.review.add(w.en, w.pt, `Mic · ${AS.name}`);
  }
  for (const [en, pt] of (x.vocab || []).slice(2)) {
    if (s.deck.length >= 12) break;
    T.review.add(en, pt, `Extra · ${x.title}`);
  }
  s.deck.forEach((c: Any, i: number) => {
    if (i % 3 === 0) {
      c.reps = 1;
      c.at = now + 2 * DAY + i * 60_000;
    } else if (i % 5 === 1) {
      c.reps = 2;
      c.at = now + 5 * DAY;
    } else {
      c.at = now - (i + 1) * 60 * 60_000;
    }
  });
  s.due = T.review.queue().length;

  // Game: 340 points over a 3-day streak ending today.
  const log: { k: string; t: number; p: number }[] = [];
  const add = (k: string, ago: number, hhmm: string, n = 1) => {
    for (let i = 0; i < n; i++) log.push({ k, t: at(ago, hhmm) + i * 60_000, p: T.game.POINTS[k] });
  };
  add('step', 2, '09:00', 2);
  add('mic_try', 2, '09:20');
  add('mic_good', 2, '09:21');
  add('maggie_turn', 2, '20:01', 4);
  add('maggie_session', 2, '20:05');
  add('extra', 1, '12:30');
  add('dub', 1, '12:40');
  add('card', 1, '13:00', 3);
  add('word', 1, '13:10');
  add('ex_right', 1, '13:20', 2);
  add('maggie_turn', 1, '19:31', 5);
  add('maggie_session', 1, '19:36');
  add('step', 0, '08:00', 2);
  add('song', 0, '08:10');
  add('mic_try', 0, '08:20', 2);
  add('mic_good', 0, '08:22');
  add('ex_right', 0, '08:40');
  add('word', 0, '09:00');
  add('card', 0, '09:10', 4);
  const day = (o: Any) => ({
    points: 0,
    steps: 0,
    cards: 0,
    maggieSec: 0,
    extras: 0,
    mic: 0,
    goal: false,
    missions: {},
    ...o,
  });
  s.game = {
    points: 340,
    streak: 3,
    lastDay: today,
    daily: {
      [dayIso(2)]: day({
        points: 120,
        steps: 2,
        maggieSec: 240,
        mic: 2,
        goal: true,
        missions: { step: true, maggie: true },
      }),
      [dayIso(1)]: day({
        points: 134,
        cards: 3,
        maggieSec: 300,
        extras: 1,
        goal: true,
        missions: { extra: true, maggie: true },
      }),
      [dayIso(0)]: day({ points: 86, steps: 2, cards: 4, mic: 3, missions: { step: true } }),
    },
    badges: ['first-step', 'mic-8', 'first-talk', 'cinema', 'dub', 'song', 'streak-3'],
    log,
  };
  return JSON.parse(JSON.stringify(s));
}

/** In-page check used by the validator: Hoje rendered, no error card, nothing new for review.sync. */
export function checkHojeInPage(): { ok: boolean; problems: string[]; h1: string; route: string } {
  const T = (window as Any).TIE;
  const problems: string[] = [];
  const text = document.body.innerText || '';
  if (/Algo deu errado nesta tela/.test(text)) problems.push('error card rendered');
  const route = T?.router?.parse?.().name ?? '';
  if (route !== 'inicio') problems.push(`route is ${route}, expected inicio`);
  const h1 = (document.querySelector('.view h1') as HTMLElement | null)?.innerText ?? '';
  if (!/^Oi, Ana\./.test(h1)) problems.push(`Hoje greeting missing (h1="${h1}")`);
  const added = T?.review?.sync?.() ?? -1;
  if (added !== 0) problems.push(`review.sync() would add ${added} cards (deck incomplete)`);
  if (T?.store?.s?.v !== 6) problems.push('state did not load as v6');
  return { ok: problems.length === 0, problems, h1, route };
}
