// `npm run seed -- --local [--persist-to <dir>]` | `npm run seed -- --remote [--force]`
// Idempotent: migrations → content + config SQL (upserts / insert-or-ignore) → media to R2 (skips
// unchanged objects) → publish (compile, content/{ver}/* to R2, content.current). Relative
// --persist-to paths resolve from apps/app, so `wrangler dev --persist-to <same>` there sees the data.
// --remote without --force never overwrites production content: missing rows only, and no publish
// once a release exists (seedPlan).
import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { parseArgs } from 'node:util';
import { SETTINGS } from '@tie/shared/constants';
import { type ConflictMode, seedStatements, sqlLiteral, toSqlFile } from './emitSql';
import { extract } from './extract';
import { loadPrototype } from './loadPrototype';
import { OUT_DIR, publish } from './publish';
import { buildConfig } from './transform/config';
import { buildContent } from './transform/content';
import { MediaIndex, scanMedia } from './transform/media';
import { uploadMedia } from './uploadMedia';
import { applyMigrations, executeFile, query, resolvePersist, type Target, targetLabel } from './wrangler';

const COUNT_TABLES = [
  'media',
  'steps',
  'seasons',
  'cast_members',
  'episodes',
  'mic_phrases',
  'exercises',
  'exercise_items',
  'ebooks',
  'ebook_test_questions',
  'extras',
  'albums',
  'album_tracks',
  'assistants',
  'assistant_clips',
  'mic_missions',
  'content_blobs',
  'option_lists',
  'point_rules',
  'levels',
  'badges',
  'plans',
  'feature_flags',
  'app_settings',
  'ai_prompts',
  'content_releases',
] as const;

export interface SeedOptions {
  skipMigrations?: boolean;
  skipMedia?: boolean;
  skipPublish?: boolean;
  /** `--force`: a remote seed overwrites content rows and republishes, like a local one. */
  force?: boolean;
  log?: (msg: string) => void;
}

export interface SeedPlan {
  contentMode: ConflictMode;
  /** 'always', or 'if-unpublished' (only when content.current is not set yet). */
  publish: 'always' | 'if-unpublished';
}

/**
 * A remote seed without --force never overwrites production content (spec 06 "Seeding"): content
 * rows an admin may have edited are only inserted when missing, and nothing is republished once
 * a release exists (publishing is the admin's call; it would ship their unpublished edits).
 */
export function seedPlan(t: Target, force = false): SeedPlan {
  return t.mode === 'remote' && !force
    ? { contentMode: 'ignore', publish: 'if-unpublished' }
    : { contentMode: 'upsert', publish: 'always' };
}

/** Builds every row from the prototype (no I/O besides reading prototipo/). */
export function buildSeed(now: number = Date.now()) {
  const D = loadPrototype();
  const X = extract();
  const files = scanMedia();
  const media = new MediaIndex(files);
  const content = buildContent(D, X, media, now);
  const config = buildConfig(X, now);
  return { D, X, files, content, config };
}

export async function seed(t: Target, opts: SeedOptions = {}) {
  const log = opts.log ?? ((m: string) => console.log(m));
  const now = Date.now();
  log(`seed → ${targetLabel(t)}`);

  const plan = seedPlan(t, opts.force);
  const { files, content, config } = buildSeed(now);
  const statements = seedStatements(content, config, { contentMode: plan.contentMode });
  mkdirSync(OUT_DIR, { recursive: true });
  const sqlFile = join(OUT_DIR, 'content.sql');
  writeFileSync(sqlFile, toSqlFile(statements, `generated by @tie/seed; ${statements.length} statements`));
  log(
    `content.sql: ${statements.length} statements (content rows: ${
      plan.contentMode === 'upsert' ? 'overwrite' : 'insert missing only; --force overwrites'
    })`,
  );

  if (!opts.skipMigrations) {
    log('migrations…');
    await applyMigrations(t);
  }
  log('content + config rows…');
  await executeFile(t, sqlFile);

  if (!opts.skipMedia) {
    log(`media (${files.length} files)…`);
    const r = await uploadMedia(t, files, log);
    log(`  media: ${r.uploaded} uploaded, ${r.skipped} unchanged`);
  }
  if (!opts.skipPublish) {
    const current =
      plan.publish === 'if-unpublished'
        ? (
            await query<{ value: string }>(
              t,
              `SELECT value FROM app_settings WHERE key = ${sqlLiteral(SETTINGS.contentCurrent)}`,
            )
          )[0]?.[0]?.value
        : undefined;
    if (current) {
      log(`publish skipped: content.current is ${current} (publish from the admin, or seed with --force)`);
    } else {
      log('publish…');
      const compiled = await publish(t, { log, now });
      log(`content.current = ${compiled.version}`);
    }
  }
  return tableCounts(t);
}

export async function tableCounts(t: Target): Promise<Record<string, number>> {
  const res = await query<{ n: number }>(t, COUNT_TABLES.map((x) => `SELECT COUNT(*) AS n FROM ${x}`).join('; '));
  return Object.fromEntries(COUNT_TABLES.map((x, i) => [x, res[i]?.[0]?.n ?? 0]));
}

async function main() {
  const { values } = parseArgs({
    options: {
      local: { type: 'boolean', default: false },
      remote: { type: 'boolean', default: false },
      'persist-to': { type: 'string' },
      'skip-migrations': { type: 'boolean', default: false },
      'skip-media': { type: 'boolean', default: false },
      'skip-publish': { type: 'boolean', default: false },
      force: { type: 'boolean', default: false },
    },
  });
  if (values.local === values.remote) {
    throw new Error('usage: npm run seed -- --local [--persist-to <dir>] | --remote [--force]');
  }
  if (values.remote && values['persist-to']) throw new Error('--persist-to only applies to --local');
  const t: Target = values.remote
    ? { mode: 'remote' }
    : { mode: 'local', persistTo: resolvePersist(values['persist-to']) };
  const counts = await seed(t, {
    skipMigrations: values['skip-migrations'],
    skipMedia: values['skip-media'],
    skipPublish: values['skip-publish'],
    force: values.force,
  });
  console.log('\nTable counts:');
  for (const [table, n] of Object.entries(counts)) console.log(`  ${table.padEnd(22)} ${n}`);
}

const isMain = process.argv[1] && /[\\/]seed[\\/]src[\\/]index\.ts$/.test(process.argv[1]);
if (isMain) {
  main().catch((err) => {
    console.error(err instanceof Error ? (err.stack ?? err.message) : err);
    process.exitCode = 1;
  });
}
