// `wrangler dev` for one slot: a generated config (a copy of apps/<app>/wrangler.jsonc with the slot's
// assets dir, port and a slot-unique Worker name), a generated .dev.vars (the app's dev vars with the
// slot origin) and, unless disabled, an entry shim that shifts the Worker clock to the frozen harness
// time so server-side "today" (streak, daily goal, quota period) matches the frozen browser clock.
import { type ChildProcess, spawn, spawnSync } from 'node:child_process';
import { copyFileSync, createWriteStream, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join, relative, resolve } from 'node:path';
import { APP_DIRS, type AppName, FROZEN_MS, type Slot } from './config';
import { parseJsonc } from './jsonc';
import { binOf, killTree, pidAlive, portFree, sleep, track, waitForHttp } from './proc';

const posix = (p: string) => p.split('\\').join('/');
const relFrom = (from: string, to: string) => {
  const r = posix(relative(from, to));
  return r.startsWith('.') ? r : `./${r}`;
};

/** apps/<app>/.dev.vars, created from .dev.vars.example when missing (foundation note). */
export function ensureDevVars(app: AppName): string {
  const dir = APP_DIRS[app];
  const vars = join(dir, '.dev.vars');
  if (!existsSync(vars)) {
    const example = join(dir, '.dev.vars.example');
    if (!existsSync(example)) throw new Error(`${example} is missing`);
    copyFileSync(example, vars);
    console.log(`created ${vars} from .dev.vars.example`);
  }
  return vars;
}

/**
 * The dev vars (text of apps/<app>/.dev.vars) for a slot: APP_ORIGIN pointed at the slot origin and
 * COOKIE_PREFIX forced to "" (the slot is plain-HTTP localhost, where a __Host- cookie is never
 * stored; a .dev.vars that lacks the line would otherwise break every login). Values are never printed.
 */
export function slotDevVars(text: string, origin: string): string {
  const forced: Record<string, string> = { APP_ORIGIN: origin, COOKIE_PREFIX: '""' };
  const seen = new Set<string>();
  const out = text.split(/\r?\n/).map((l) => {
    const m = /^\s*([A-Z_][A-Z0-9_]*)\s*=/.exec(l);
    const name = m?.[1];
    if (name && name in forced) {
      seen.add(name);
      return `${name}=${forced[name]}`;
    }
    return l;
  });
  while (out.length && out[out.length - 1] === '') out.pop();
  for (const [name, value] of Object.entries(forced)) if (!seen.has(name)) out.push(`${name}=${value}`);
  return `${out.join('\n')}\n`;
}

/**
 * The Worker clock shim: `Date` shifted by `offset` ms. A plain function (not a class), so both
 * `new Date(...)` and the legal call form `Date()` (which returns a string) keep working, and
 * subclasses (`class X extends Date`) still get their own prototype through new.target.
 */
export function clockShimSource(offset: number): string {
  return [
    '// Generated by tools/parity: the Worker sees the frozen harness time (plus elapsed real time).',
    `const OFFSET = ${Math.trunc(offset)};`,
    'const RealDate = globalThis.Date;',
    'const shiftedNow = () => RealDate.now() - OFFSET;',
    'function ParityDate(...args) {',
    '  if (!new.target) return new RealDate(shiftedNow()).toString();',
    '  return Reflect.construct(RealDate, args.length === 0 ? [shiftedNow()] : args, new.target);',
    '}',
    'Object.setPrototypeOf(ParityDate, RealDate);',
    'for (const k of Object.getOwnPropertyNames(RealDate)) {',
    "  if (k === 'prototype' || k === 'length' || k === 'name') continue;",
    '  Object.defineProperty(ParityDate, k, Object.getOwnPropertyDescriptor(RealDate, k));',
    '}',
    "Object.defineProperty(ParityDate, 'prototype', { value: RealDate.prototype, writable: false });",
    "Object.defineProperty(ParityDate, 'now', { value: function now() { return shiftedNow(); }, writable: true, configurable: true });",
    'globalThis.Date = ParityDate;',
    '',
  ].join('\n');
}

export interface DevServerOpts {
  app: AppName;
  slot: Slot;
  /** Real wall clock in the Worker instead of the frozen harness time. */
  realClock?: boolean;
  /** Wall-clock instant mapped to FROZEN_MS (fixtures are written with now = FROZEN_MS). */
  clockAnchor?: number;
  /** Keep the remote-only Workers AI binding (needs CLOUDFLARE_API_TOKEN). */
  keepAi?: boolean;
}

export interface DevServer {
  origin: string;
  logFile: string;
  stop(): Promise<void>;
}

function generate(o: DevServerOpts): { config: string; dir: string } {
  const { app, slot: sl } = o;
  const appDir = APP_DIRS[app];
  const dir = sl.genDir(app);
  mkdirSync(dir, { recursive: true });
  const cfg = parseJsonc<Record<string, unknown>>(readFileSync(join(appDir, 'wrangler.jsonc'), 'utf8'));
  const main = resolve(appDir, String(cfg.main));

  let entry = main;
  if (!o.realClock) {
    const offset = (o.clockAnchor ?? Date.now()) - FROZEN_MS;
    writeFileSync(join(dir, 'parity-clock.mjs'), clockShimSource(offset));
    const rel = relFrom(dir, main);
    writeFileSync(
      join(dir, 'parity-entry.ts'),
      [
        '// Generated by tools/parity: clock shim first, then the real Worker.',
        "import './parity-clock.mjs';",
        `export * from '${rel}';`,
        `export { default } from '${rel}';`,
        '',
      ].join('\n'),
    );
    entry = join(dir, 'parity-entry.ts');
  }

  const out: Record<string, unknown> = { ...cfg };
  delete out.$schema;
  out.name = `${String(cfg.name)}-parity-s${sl.n}`;
  // Workers AI only exists remotely: wrangler dev would open a remote proxy session that needs a
  // Cloudflare API token. The harness runs the app in demo mode (/api/health → {ai:false}), so the
  // binding is dropped and every AI path takes its demo fallback, offline.
  if (!o.keepAi) delete out.ai;
  // The `local` environment (npm run dev) is not used here, and its relative paths would not resolve
  // from the generated directory.
  delete out.env;
  // Admin shots: every super_admin job shares one staff user, and RL_API is keyed by user (100 per
  // 10 s), so a parallel capture of every screen would hit 429s that no real admin sees. Only RL_API
  // is lifted; the auth / AI / upload limits stay as configured.
  if (app === 'admin' && Array.isArray(cfg.ratelimits)) {
    out.ratelimits = (cfg.ratelimits as Record<string, unknown>[]).map((r) =>
      r.name === 'RL_API' ? { ...r, simple: { limit: 100_000, period: 10 } } : r,
    );
  }
  out.main = relFrom(dir, entry);
  out.dev = { ...(cfg.dev as object), port: sl.appPort, inspector_port: sl.inspectorPort };
  const assets = { ...(cfg.assets as Record<string, unknown>) };
  assets.directory = relFrom(dir, sl.distDir(app));
  out.assets = assets;
  out.d1_databases = ((cfg.d1_databases as Record<string, unknown>[]) ?? []).map((d) => ({
    ...d,
    ...(d.migrations_dir ? { migrations_dir: relFrom(dir, resolve(appDir, String(d.migrations_dir))) } : {}),
  }));
  const config = join(dir, 'wrangler.jsonc');
  writeFileSync(
    config,
    `// Generated by tools/parity for slot ${sl.n} (${app}); do not edit.\n${JSON.stringify(out, null, 2)}\n`,
  );
  writeFileSync(join(dir, '.dev.vars'), slotDevVars(readFileSync(ensureDevVars(app), 'utf8'), sl.origin));
  return { config, dir };
}

const pidFile = (o: DevServerOpts) => join(o.slot.genDir(o.app), 'wrangler.pid');

/** Kills a wrangler left running by a crashed run of this same slot (only node/workerd processes). */
function killStale(o: DevServerOpts): void {
  const f = pidFile(o);
  if (!existsSync(f)) return;
  const pid = Number(readFileSync(f, 'utf8'));
  rmSync(f, { force: true });
  if (!pid || !pidAlive(pid)) return;
  if (process.platform === 'win32') {
    const r = spawnSync('tasklist', ['/FI', `PID eq ${pid}`, '/FO', 'CSV', '/NH'], {
      encoding: 'utf8',
      windowsHide: true,
    });
    if (!/node\.exe|workerd/i.test(r.stdout ?? '')) return;
  }
  console.log(`killing stale wrangler (pid ${pid}) from a previous run of slot ${o.slot.n}`);
  killTree(pid);
}

export async function startDevServer(o: DevServerOpts): Promise<DevServer> {
  killStale(o);
  const { slot: sl, app } = o;
  for (const port of [sl.appPort, sl.inspectorPort]) {
    let free = await portFree(port);
    for (let i = 0; !free && i < 10; i++) {
      await sleep(500);
      free = await portFree(port);
    }
    if (!free) throw new Error(`port ${port} (slot ${sl.n}) is in use; is another run using slot ${sl.n}?`);
  }
  const { config, dir } = generate(o);
  const logFile = join(dir, 'wrangler.log');
  const log = createWriteStream(logFile);
  const wrangler = binOf('wrangler', join('bin', 'wrangler.js'));
  const child: ChildProcess = track(
    spawn(
      process.execPath,
      [
        wrangler,
        'dev',
        '--config',
        config,
        '--port',
        String(sl.appPort),
        '--inspector-port',
        String(sl.inspectorPort),
        '--ip',
        'localhost',
        '--persist-to',
        sl.persistAbs,
        '--show-interactive-dev-session=false',
      ],
      {
        cwd: dirname(config),
        env: { ...process.env, CI: '1', WRANGLER_SEND_METRICS: 'false', NO_COLOR: '1', FORCE_COLOR: '0' },
        stdio: ['ignore', 'pipe', 'pipe'],
        windowsHide: true,
      },
    ),
  );
  child.stdout?.pipe(log);
  child.stderr?.pipe(log);
  writeFileSync(pidFile(o), String(child.pid ?? ''));
  let exited: string | null = null;
  child.on('exit', (code) => {
    exited = `wrangler dev (slot ${sl.n}) exited with ${code}; see ${logFile}`;
  });
  const stop = async () => {
    if (child.exitCode === null) killTree(child);
    rmSync(pidFile(o), { force: true });
    await new Promise<void>((r) => log.end(() => r()));
  };
  try {
    const probe = app === 'app' ? '/api/health' : '/';
    await waitForHttp(`${sl.origin}${probe}`, 120_000, () => exited);
  } catch (err) {
    await stop();
    const tail = existsSync(logFile) ? readFileSync(logFile, 'utf8').slice(-3000) : '';
    throw new Error(`${(err as Error).message}\n--- ${logFile} ---\n${tail}`);
  }
  return { origin: sl.origin, logFile, stop };
}
