// Componentes: devolvem HTML. Eventos por delegação: data-act="acao" data-arg="…" e data-go="rota".
window.TIE = window.TIE || {};
(function () {
  const { esc } = TIE.u, I = (n, s, x) => TIE.icon(n, s, x), C = {};
  C.logo = (o) => { o = Object.assign({ size: 20, desc: false, white: false }, o); return '<div class="logo' + (o.white ? ' w' : '') + '" style="font-size:' + o.size + 'px" aria-label="Take It Easy"><div class="wm"><span>TAKE IT</span><span class="el" aria-hidden="true"><i></i><i></i><i></i></span><span>EASY</span></div>' + (o.desc ? '<div class="desc" style="font-size:.3em">INGLÊS PARA QUEM FALA PORTUGUÊS</div>' : '') + '</div>'; };
  C.btn = (label, o) => { o = Object.assign({ kind: '', act: '', arg: '', go: '', icon: '', iconR: '', cls: '', dis: false, kicker: '' }, o); const attrs = (o.act ? ' data-act="' + o.act + '"' : '') + (o.arg !== '' ? ' data-arg="' + esc(o.arg) + '"' : '') + (o.go ? ' data-go="' + o.go + '"' : '') + (o.dis ? ' disabled' : ''); return '<button class="btn ' + o.kind + ' ' + o.cls + '"' + attrs + '>' + (o.icon ? I(o.icon, 20) : '') + (o.kicker ? '<span><span class="kicker">' + esc(o.kicker) + '</span>' + esc(label) + '</span>' : '<span>' + esc(label) + '</span>') + (o.iconR ? I(o.iconR, 20) : '') + '</button>'; };
  C.chip = (label, o) => { o = Object.assign({ on: false, act: '', arg: '' }, o); return '<button class="chip' + (o.on ? ' on' : '') + '" data-act="' + o.act + '" data-arg="' + esc(o.arg) + '" aria-pressed="' + o.on + '"><span class="ck">' + (o.on ? I('check', 12) : '') + '</span>' + esc(label) + '</button>'; };
  C.toggle = (on, act, arg, label) => '<button class="toggle' + (on ? ' on' : '') + '" data-act="' + act + '" data-arg="' + (arg || '') + '" role="switch" aria-checked="' + !!on + '" aria-label="' + esc(label || '') + '"><i></i></button>';
  C.topbar = (o) => { o = Object.assign({ back: '', title: '', kicker: '', right: '' }, o); return '<header class="topbar">' + (o.back ? '<button class="iconbtn" data-go="' + o.back + '" aria-label="Voltar">' + I('back', 20) + '</button>' : '') + '<div class="ttl">' + (o.kicker ? '<div class="lbl">' + esc(o.kicker) + '</div>' : '') + (o.title ? '<div class="h2" style="margin-top:2px">' + esc(o.title) + '</div>' : '') + '</div>' + (o.right || '') + '</header>'; };
  C.userPic = (size) => { const s = TIE.store.s, p = s.profile || {}, src = p.photo || (TIE.avatar.DIR + 'user-' + (p.avatar || 1) + '.webp'); return '<img class="userpic" src="' + src + '" alt="" style="width:' + (size || 42) + 'px;height:' + (size || 42) + 'px">'; };
  // Seletor do assistente do Mic (tela do Mic e Perfil). act recebe a chave do personagem.
  C.assistPicker = (act) => { const cur = TIE.assist.cur(); return '<div class="assist-row" role="radiogroup" aria-label="Seu assistente">' + TIE.assist.list.map((a) => '<button class="assist' + (a.k === cur.k ? ' on' : '') + '" role="radio" aria-checked="' + (a.k === cur.k) + '" data-act="' + act + '" data-arg="' + a.k + '">' + TIE.avatar.thumb(a.k) + '<b>' + esc(a.name) + '</b><span>' + esc(a.tag) + '</span></button>').join('') + '</div>'; };
  C.avatarBtn = () => '<button class="avatarbtn" data-go="perfil" aria-label="Perfil" title="Seu perfil">' + C.userPic(42) + '<span class="ed">' + I('profile', 11) + '</span></button>';
  C.demoBadge = () => TIE.ai.online ? '<span class="demo-badge live"><i></i>IA ligada</span>' : '<span class="demo-badge"><i></i>Modo demo</span>';
  C.segs = (cur, reached) => '<div class="segs">' + TIE.data.STEPS.map((x) => '<i class="' + (x.n < cur || (x.n <= reached && x.n !== cur) ? 'done' : x.n === cur ? 'now' : '') + (x.n === 4 || x.n === 10 ? ' sep' : '') + '"></i>').join('') + '</div>';
  C.ring = (pct, label, o) => { o = Object.assign({ lg: false, color: '' }, o); const r = 26, c = 2 * Math.PI * r; return '<div class="ring' + (o.lg ? ' lg' : '') + '"><svg viewBox="0 0 64 64"><circle class="bg" cx="32" cy="32" r="' + r + '"/><circle class="fg" cx="32" cy="32" r="' + r + '" stroke-dasharray="' + c.toFixed(1) + '" stroke-dashoffset="' + (c * (1 - Math.min(100, pct) / 100)).toFixed(1) + '"' + (o.color ? ' style="stroke:' + o.color + '"' : '') + '/></svg><div class="val">' + label + '</div></div>'; };
  C.gamebar = () => { const g = TIE.game.summary(); return '<div class="gamebar"><a class="g streak" href="#/conquistas"><span class="ic">' + I('fire', 16) + '</span><span><b>' + g.streak + '</b><small>sequência</small></span></a><a class="g pts" href="#/conquistas"><span class="ic">' + I('coin', 16) + '</span><span><b>' + g.points + '</b><small>pontos</small></span></a><a class="g goal" href="#/inicio"><span class="ic">' + I('target', 16) + '</span><span><b>' + g.goal.done + '/' + g.goal.target + '</b><small>meta hoje</small></span></a></div>'; };
  C.levelpill = () => { const l = TIE.game.summary().level; return '<span class="levelpill"><i>' + l.n + '</i>' + esc(l.name) + '</span>'; };
  C.cover = (x, o) => { o = Object.assign({ why: true, go: 'extra/' + x.id }, o); return '<button class="cover" data-go="' + o.go + '" aria-label="' + esc(x.title) + '"><div class="art"><img src="' + x.cover + '" alt="" loading="lazy"><span class="pill lvl lv">' + esc(x.level) + '</span>' + (x.locked ? '<div class="lock"><span class="pill or">' + I('lock', 13) + ' Sexta</span></div>' : '') + '</div><div class="ttl">' + esc(x.title) + '</div><div class="xs">' + esc(x.kind) + '</div>' + (o.why && x.why ? '<div class="why">' + esc(x.why) + '</div>' : '') + '</button>'; };
  // Carrossel 3D de capas. Comportamento em C.flowMount(el).
  C.flow = (items, id) => '<div class="flow" id="' + id + '" data-n="' + items.length + '">' + items.map((x, i) => '<div class="item" data-i="' + i + '" data-go="extra/' + x.id + '"><img src="' + x.cover + '" alt="" draggable="false"><div class="cap"><b>' + esc(x.title) + '</b><span>' + esc(x.kind) + ' · ' + esc(x.level) + '</span></div></div>').join('') + '<button class="arrow l" data-flow="-1" aria-label="Anterior">' + I('back', 18) + '</button><button class="arrow r" data-flow="1" aria-label="Próxima">' + I('next', 18) + '</button><div class="dots">' + items.map((_, i) => '<i data-dot="' + i + '"></i>').join('') + '</div></div>';
  C.flowMount = (el, o) => {
    if (!el) return { destroy() {} };
    o = Object.assign({ start: 0, auto: 3800 }, o);
    const items = [...el.querySelectorAll('.item')], dots = [...el.querySelectorAll('[data-dot]')], n = items.length; let cur = o.start, timer = 0, dragX = null, moved = false;
    const layout = () => {
      const desk = el.clientWidth > 700, gapX = desk ? 190 : 120;
      items.forEach((it, i) => { let d = i - cur; if (d > n / 2) d -= n; if (d < -n / 2) d += n; const ad = Math.abs(d); it.style.transform = 'translateX(' + (d * gapX) + 'px) translateZ(' + (-ad * 160) + 'px) rotateY(' + (-d * 28) + 'deg) scale(' + (1 - ad * .08) + ')'; it.style.opacity = ad > 2 ? 0 : 1 - ad * .18; it.style.zIndex = 10 - ad; it.style.filter = ad ? 'brightness(' + (1 - ad * .25) + ')' : 'none'; it.classList.toggle('on', d === 0); });
      dots.forEach((dt, i) => dt.classList.toggle('on', i === cur));
    };
    const go = (d) => { cur = (cur + d + n) % n; layout(); };
    const arm = () => { clearInterval(timer); if (o.auto) timer = setInterval(() => go(1), o.auto); };
    el.addEventListener('click', (ev) => { const a = ev.target.closest('[data-flow]'); if (a) { ev.stopPropagation(); go(+a.getAttribute('data-flow')); arm(); return; } const it = ev.target.closest('.item'); if (it && !moved) { const i = +it.getAttribute('data-i'); if (i !== cur) { ev.stopPropagation(); ev.preventDefault(); cur = i; layout(); arm(); } } });
    el.addEventListener('pointerdown', (ev) => { dragX = ev.clientX; moved = false; });
    el.addEventListener('pointermove', (ev) => { if (dragX == null) return; const dx = ev.clientX - dragX; if (Math.abs(dx) > 40) { go(dx < 0 ? 1 : -1); dragX = ev.clientX; moved = true; arm(); } });
    el.addEventListener('pointerup', () => { dragX = null; setTimeout(() => { moved = false; }, 50); });
    layout(); arm();
    return { destroy() { clearInterval(timer); } };
  };
  C.missions = (list) => '<div>' + list.map((m) => '<a class="mission' + (m.done ? ' done' : '') + '" href="#/' + m.go + '"><span class="ck">' + (m.done ? I('check', 16) : '') + '</span><span class="grow"><span class="h3" style="display:block;font-size:1rem">' + esc(m.t) + '</span></span><span class="pill gold">+15</span></a>').join('') + '</div>';
  C.stage = (o) => { o = Object.assign({ id: 'av', bg: 'assets/img/gen/bg/maggie-set.webp', status: '', caption: '', listening: false, cls: '' }, o); return '<div class="avatar-stage ' + o.cls + '" id="' + o.id + '"><div class="bg" style="background-image:url(' + o.bg + ')"></div>' + (o.status ? '<span class="status' + (o.listening ? ' listen' : '') + '"><i></i>' + esc(o.status) + '</span>' : '') + (o.listening ? '<div class="eq">' + [0, 1, 2, 3, 4].map((i) => '<i style="animation-delay:' + i * .12 + 's"></i>').join('') + '</div>' : '') + (o.caption || '') + '</div>'; };

  const NAV = [['inicio', 'Hoje', 'home'], ['trilha', 'Trilha', 'trail'], ['extra', 'EXTRA', 'tv'], ['maggie', 'Mic', 'mic'], ['perfil', 'Você', 'profile']];
  // No rodapé do celular, Revisão (cartões) ocupa o lugar de Você; o perfil segue no avatar do topo.
  const TABS = NAV.slice(0, 4).concat([['revisao', 'Revisão', 'cards']]);
  C.tabbar = (active) => '<nav class="tabbar" aria-label="Navegação">' + TABS.map(([k, l, ic]) => '<a class="tab' + (active === k ? ' on' : '') + '" href="#/' + k + '"><span class="ico">' + I(ic, 22) + (k === 'revisao' && TIE.store.s.due ? '<b class="badge">' + TIE.store.s.due + '</b>' : '') + '</span><span>' + l + '</span></a>').join('') + '</nav>';
  C.side = (active) => { const s = TIE.store.s, g = TIE.game.summary(); return '<aside class="side on-navy">' + C.logo({ size: 19, white: true }) + NAV.map(([k, l, ic]) => '<a class="nav' + (active === k ? ' on' : '') + '" href="#/' + k + '">' + I(ic, 21) + '<span>' + (k === 'extra' ? 'EXTRA' : l) + '</span></a>').join('') + '<a class="nav' + (active === 'revisao' ? ' on' : '') + '" href="#/revisao">' + I('cards', 21) + '<span>Revisão</span>' + (s.due ? '<span class="badge">' + s.due + '</span>' : '') + '</a><a class="nav' + (active === 'conquistas' ? ' on' : '') + '" href="#/conquistas">' + I('trophy', 21) + '<span>Conquistas</span></a>' + '<div class="foot"><div class="card" style="background:var(--navy2);border-color:var(--navy2);padding:14px"><div class="row between"><span class="lbl">Meta de hoje</span><span class="sm" style="color:#fff;font-weight:800">' + g.goal.done + '/' + g.goal.target + '</span></div><div class="bar mt8"><i style="width:' + g.goal.pct + '%"></i></div><div class="row mt12" style="--gap:8px">' + C.levelpill() + '<span class="xs">' + g.streak + ' dias seguidos</span></div></div></div></aside>'; };
  TIE.C = C;
})();
